### ISSUE TITLE
Permission error MacOS

### ISSUE THREAD

**Issue by norcalskeptic** [invoke-ai/InvokeAI#692] opened 2022-09-19 05:13 UTC
Struggling to help my friend install on his Mac.

- OS: macOS

Made it all the way through install, but when trying to run dream.py get the following error:

(ldm) The-Void-Mirror:stable-diffusion JasonM$ python scripts/dream.py --full_precision
Traceback (most recent call last):
  File "/Users/JasonM/stable-diffusion/scripts/dream.py", line 12, in <module>
    import ldm.dream.readline
  File "/Users/JasonM/stable-diffusion/ldm/dream/readline.py", line 123, in <module>
    readline.read_history_file(histfile)
PermissionError: [Errno 13] Permission denied

I'm not familiar with MacOS, did my best to help him but can't seem to get past this step, would appreciate any help.
<img width="1001" alt="Screen_Shot_2022-09-18_at_10 08 31_PM" src="https://user-images.githubusercontent.com/10851963/190953385-70dbbe3d-dfba-4f5b-bada-59c10e24b483.png">

Thanks!

**Comment by tildebyte** [comment] 2022-09-19 23:54
Guessing, here, but check the location and permissions thereof for '~/.dream_history'. If it doesn't exist, try creating it.

Note; IDK the level of *nix proficiency here, but '~' represents the **users**'s home directory, so the permissions issue isn't there (the system would be too fouled up to use if so). There's something going on with the '.dream_history' dir in the user's home directory.

**Comment by psychedelicious** [comment] 2022-10-20 13:27
Hi @norcalskeptic , is this still an issue?

**Comment by Kirkman** [comment] 2022-11-18 19:16
I'm experiencing the same issue on an M1 2020 MacBook Air. I can get the web UI to run, but not the command line version.

Here's the error message:

<img width="716" alt="screenshotx" src="https://user-images.githubusercontent.com/761387/202783755-4bf5ae76-6c5b-4932-a4f3-cb3c693a6be4.png">

As far as I can tell, `opt.outdir` is resolving to `outputs/img-samples/`. I tried creating `outputs/img-samples/.invoke_history` and setting 777 permissions, but the error is still occurring.

I believe the issue is probably Mac/readline specific. I see other Mac users have reported the same `Operation not permitted` error with readline in [other contexts](https://apple.stackexchange.com/questions/275447/why-does-pythons-readline-read-history-file-not-work-from-a-script-but-work-in).

**Comment by Kirkman** [comment] 2022-11-18 19:37
After further research, it appears that the [Mac needs](https://stackoverflow.com/a/29572581/566307) `gnureadline` rather than `readline`.

I was able to get the command line to load correctly after:

1. Installing `gnureadline` via pip
2. Changing readline.py as follows:
```
try:
    import gnureadline as readline
    readline_available = True
except:
    try:
        import readline
        readline_available = True
    except (ImportError,ModuleNotFoundError):
        readline_available = False
```

**Comment by psychedelicious** [comment] 2022-11-18 20:24
@Kirkman Thanks for troubleshooting. I'm also on an M1 Macbook - and many of our users are as well - but this seems to be a very rare issue. I cannot recreate it. 

I'm very skeptical that `gnureadline` is needed - see the big `STOP` blurb on the package details here: https://pypi.org/project/gnureadline/

How did you install invokeai and set up its venv? I wonder if something funky happened along the way...

**Comment by Kirkman** [comment] 2022-11-18 20:48
I used `pyenv` to install Python 3.9 and create a virtualenv. Then I followed the pip instructions under the manual install.

But I have noticed some oddities about the way pyenv's virtualenvs are functioning. So, yes, it's possible there's something funky going on.

What I can say for sure is that before switching to gnureadline, I absolutely could not get the command line to work (though the web UI works fine). After making changes to use gnureadline, the Invoke command line works.

**Comment by psychedelicious** [comment] 2022-11-18 21:05
@Kirkman Ok, thanks. Given the big warning on the `gnureadline` PyPi homepage, I don't think we should change the dependency, but I'm not a python-y person. Paging @tildebyte

**Comment by tildebyte** [comment] 2022-11-18 21:10
...who in turn is paging @lstein. I helped figure out how to get readline going on Windows, but I don't have a clue on MacOS...

**Comment by psychedelicious** [comment] 2022-11-22 21:18
Sorry @Kirkman , I don't think we have any idea on how to fix this for your specific case. I think your installation is... unique, let's say... for unknown reasons. Glad you found a fix though and I'll remember this issue if we see this come up again.

**Closed by psychedelicious** 2022-11-22 21:18 UTC
Labels: bug
