### ISSUE TITLE
[bug]: In Unified Canvas, after long processing, there is no staging area toolbar buttons

### ISSUE THREAD

**Issue by KittQB** [invoke-ai/InvokeAI#2885] opened 2023-03-07 14:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cpu

### VRAM

4GB

### What happened?

I'm using cpu only processing. For large images, after a couple of minutes the server gets "disconnected" status. After processing is finished, the server is reconnected - but the staging area toolbar buttons are not appearing, and the final image is not shown (it could be found in temp only). The "automatic save" option doesn't help as well. The similar option is also in Text2Image and Image2Image - but then simple screen refresh helps. In unified canvas nothing can bring the final image to the screen.

**Comment by KittQB** [comment] 2023-03-23 14:55
During the processing, server gets disconnected:
![2023-03-23_15-42-03](https://user-images.githubusercontent.com/61204294/227242275-9f4aa42c-3ce7-4a19-868b-de50e0f164cc.jpg)
after processing is finished, the server reconnects, but the finished picture is not received and the staging area toolbar doesn't appear:
![2023-03-23_15-48-34](https://user-images.githubusercontent.com/61204294/227242317-525442ef-95a7-42e7-8f76-8a9b1ccbf389.jpg)

**Comment by KittQB** [comment] 2023-03-28 13:33
I've updated to 3.0.0+a0 and the issue is still being experienced.

![image](https://user-images.githubusercontent.com/61204294/228253626-7cca6210-152b-4b76-ba89-02d7f3b20f1d.png)

**Comment by arizona991998** [comment] 2023-04-08 15:07
![image](https://user-images.githubusercontent.com/45437110/230728550-93f01df8-2595-453a-b714-195305ee88e2.png)
just empty temp image folder on setting

**Comment by psychedelicious** [comment] 2023-04-10 11:17
This will not be a problem after we finish migrating to the nodes server.

**Comment by RicoRaw** [comment] 2023-05-03 19:05
I've been experiencing this issue on one of my underpowered computers. Been running CPU rendering, so rendering is slow. After about 4 minutes it disconnects every time. I thought it was a simple browser timeout. Once image is done it reconnects so no biggie. It's my travel laptop, so not the end of the world. This makes using Unified Canvas completely unusable, because upon reconnection, there are no buttons. I wish there was a way to force a "System config requested" call from within browser or disable timeouts (if that's even the cause). Who knows. Invoke has a long way to go in development, so maybe in the future it won't be an issue.

**Comment by psychedelicious** [comment] 2023-05-03 23:07
This is related to the synchronous nature of the web server script (socketio connection times out). It's not really possible to fix the web server due to how it was built. 

We have a massive backend redesign that resolves this issue (new web server, engine, etc). This will be in our 3.0.0 release. You can try it out on the main branch, but we can't offer support for it as it is pre-alpha.

**Comment by KittQB** [comment] 2023-05-19 10:54
I updated to main branch - and still the same. @psychedelicious  Is it that release with the new web server?
![image](https://github.com/invoke-ai/InvokeAI/assets/61204294/32270021-357b-4528-9d7a-5c0fec29da01)

**Closed** 2023-07-02 12:48 UTC
Labels: bug
