### ISSUE TITLE
SD 1.5 models (.savetensor) cannot be imported via autoimport

### ISSUE THREAD

**Issue by MarcoBlumenthal** [invoke-ai/InvokeAI#4827] opened 2023-10-08 22:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12GB

### What version did you experience this issue on?

3.2.0

### What happened?

i downloaded some checkpoint models from civitai and placed them into the autoimport folder. when starting invoke.bat, i get this on the console:
...
[2023-10-08 23:45:21,741]::[InvokeAI]::INFO --> GPU device = cuda NVIDIA GeForce RTX 3060
[2023-10-08 23:45:21,841]::[InvokeAI]::INFO --> Scanning F:\InvokeAI\models for new models

Please select the type of the V2 checkpoint named photogenesis_v30.safetensors:
[1] A model based on Stable Diffusion v2 trained on 512 pixel images (SD-2-base)
[2] A model based on Stable Diffusion v2 trained on 768 pixel images (SD-2-768)
[3] Skip this model and come back later.

select> 3

Please select the type of the V2 checkpoint named realisticVisionV51_v51VAE.safetensors:
[1] A model based on Stable Diffusion v2 trained on 512 pixel images (SD-2-base)
[2] A model based on Stable Diffusion v2 trained on 768 pixel images (SD-2-768)
[3] Skip this model and come back later.

select> 3

Please select the type of the V2 checkpoint named reliberate_v20.safetensors:
[1] A model based on Stable Diffusion v2 trained on 512 pixel images (SD-2-base)
[2] A model based on Stable Diffusion v2 trained on 768 pixel images (SD-2-768)
[3] Skip this model and come back later.

select> 3

Please select the type of the V2 checkpoint named sweetMint_v10.safetensors:
[1] A model based on Stable Diffusion v2 trained on 512 pixel images (SD-2-base)
[2] A model based on Stable Diffusion v2 trained on 768 pixel images (SD-2-768)
[3] Skip this model and come back later.

select> 3
[2023-10-08 23:46:05,357]::[InvokeAI]::INFO --> Scanned 12 files and directories, imported 4 models
[2023-10-08 23:46:05,435]::[InvokeAI]::INFO --> Model manager service initialized
[2023-10-08 23:46:05,435]::[InvokeAI]::INFO --> Pruned 0 finished queue items

it seems that the files are recognized as SD 2.x files, but they are SD1.5 based. I skipped the models by selecting option 3, nevertheless, the models appear as SD1 checkpoints in the model manager. But they cannot be converted into diffusor models.
see screenshot.
the models can be selected in the models combo box e.g. in the text to image page, but no images can be generated: server error.

models previously imported and converted with invokeAI 3.1.x work fine

### Screenshots

![fail](https://github.com/invoke-ai/InvokeAI/assets/34511086/b25f0fff-cc55-4e3f-a1b2-9d90bbc1279a)

### Contact Details

marco.blumenthal@gmx.de

**Comment by Millu** [comment] 2023-10-12 07:13
Duplicate of #4768

**Closed** 2023-10-13 02:27 UTC
Labels: bug, model manager
