### ISSUE TITLE
[enhancement]: 77 maximum tokens?

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#1541] opened 2022-11-23 23:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Hello, any specific reason why there is a hard cap of the maximum number of tokens?

merge_embeddings.py line 28
max_length=77,

One would think tokens would be discarded based on relevance but they are simply trimmed after the 77th token.

**Comment by n00mkrad** [comment] 2022-11-24 07:42
CLIP does not support more than that.

**Comment by Neosettler** [comment] 2022-11-24 19:10
the limit have been lifted here:

[max_position_embeddings (int, optional, defaults to 77) — The maximum sequence length that this model might ever be used with. Typically set this to something large just in case (e.g., 512 or 1024 or 2048).](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/706d5944a075a6523ea7f00165d630efc085ca22)

I read somewhere that this change have been reverted for unknown reason, might worth investigating.

**Comment by n00mkrad** [comment] 2022-11-24 19:39
This likely won't be ported due to political/PR reasons - The CLIP token limit removal is based on leaked NovelAI knowledge.

**Comment by Neosettler** [comment] 2022-11-25 21:30
Yikes, I didn't know that. Well, cant erased the fact that it is possible. Having max tokens capped to 77 due to political/PR reasons seems to me like a crime against humanity.

**Comment by psychedelicious** [comment] 2022-11-26 07:22
Could have sworn that this was a toggle on A1111 from before the NovelAI situation... hmm

**Comment by n00mkrad** [comment] 2022-11-26 14:37
> Could have sworn that this was a toggle on A1111 from before the NovelAI situation... hmm

99% sure that's not the case, it was added just days after the leak, if not on the same

**Comment by psychedelicious** [comment] 2022-11-26 20:15
> 99% sure that's not the case, it was added just days after the leak, if not on the same

Yeah, the dates on the commit match. My mistake

**Comment by Neosettler** [comment] 2022-11-26 20:18
so... unfortunate circumstances for this particular case aside, could we skip to the part where this feature would be a great addition or there is no way other way to implement this without asking for trouble?

**Comment by keturn** [comment] 2022-12-02 17:14
I had a look at the implementation here: https://github.com/huggingface/diffusers/blob/main/examples/community/lpw_stable_diffusion.py#L209

My initial take after reading this is: this is something that wouldn't be too difficult to add. With or without diffusers doesn't make much difference, everyone is using transformers.CLIPTextModel to turn text to CLIP embeddings, and all the weighting and blending InvokeAI does means it is already messing with that stuff anyway.

It is not quite as simple as pretending the token limit doesn't exist. You still can only send that many through CLIPTextModel at one time. but apparently if you feel like it, you can do that a couple times and concatenate them all together and send the whole mess to the diffusion model?

I think the biggest unknowns will be:
- Like giving the diffusion model latents that aren't 512 (encoded to 64) square, if you change the dimensions on it, it might do weird shit. In this case we're changing the dimensions of the embeddings instead of the latents, to something different than what it was trained on.
- When preparing those embeddings in chunks, it might matter how you divide up those chunks. The most obvious case is if you have a multi-token word, I have a strong suspicion that it won't be represented very well if it gets chopped in half and the first syllable is at the end of one embedding and the rest of it is in the next.

**Comment by keturn** [comment] 2022-12-02 17:15
Personal recommendation: this isn't something that should be done transparently by default.

First, focus on some UI features to make it more visible how InvokeAI is interpreting your prompt. e.g. what the positive and negative prompts are (conditioning and un-conditioned), whether it is splitting and blending multiple prompts, etc. This information is currently available in a very dense syntax-heavy format if you use log-tokenization in the TUI, but is invisible to the Web UI, and you only know about it _after_ you start things generating.

_Then_ we can build on that and show if your long prompt is split in to multiple embeddings, _where_ it is split, etc.

**Comment by hipsterusername** [comment] 2022-12-04 22:45
Would love to hear ideas on how we move closer to this, and what the implications are on the prompt. We’re contemplating the prompt crafting UX and think this is going to have to play mightily into it

**Comment by Seedmanc** [comment] 2022-12-13 09:03
Novel has stolen from SD first, why do we even care. The cat is out of the bag anyway.

**Comment by n00mkrad** [comment] 2022-12-13 10:22
> Novel has stolen from SD first, why do we even care. The cat is out of the bag anyway.

SD is Open Source, you can't steal from it.
NovelAI is not.

**Comment by Seedmanc** [comment] 2022-12-13 11:38
Is open-source allowed to be used for profit though? I recall many licenses prohibit that kind of thing.

**Comment by hipsterusername** [comment] 2022-12-13 12:11
Yes. For example, InvokeAI is MIT licensed and can (and is) used to build for profit commercial products

**Comment by feffy380** [comment] 2022-12-16 12:19
Given that NAI themselves describe their technique in a [public blog post](https://blog.novelai.net/novelai-improvements-on-stable-diffusion-e10d38db82ac), it should be entirely possible to implement without referencing any "tainted" code.

**Comment by hipsterusername** [comment] 2022-12-16 12:38
@feffy380 they don’t seem to provide any code? 

At this point, we’re sufficiently convinced it would be ok to implement so long as we have something TO reference in implementing (that isn’t autos code)

**Comment by Neosettler** [comment] 2022-12-16 22:48
> and all the weighting and blending InvokeAI does means it is already messing with that stuff anyway.

Not liking the sound of that. I was under the impression that given the same parameters, Automatic111 and Invoke AI (or any other SD fork for that matter) would spit the same results/identical image. Apparently the Frankenstein-ism has begun a long time ago.

**Comment by hyperjesus88** [comment] 2022-12-20 22:56
the limit-removal code right on the AUTOMATIC webui repository has changed from what @Neosettler linked at the top and i'm pretty sure it's original now

**Comment by n00mkrad** [comment] 2022-12-21 03:26
> the limit-removal code right on the AUTOMATIC webui repository has changed from what @Neosettler linked at the top and i'm pretty sure it's original now

Link to code or commit?

**Comment by ResidentChief** [comment] 2023-02-02 09:46
https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/706d5944a075a6523ea7f00165d630efc085ca22 @n00mkrad - I think

**Comment by Testertime** [comment] 2023-02-04 04:42
This limit is what keeps me from using InvokeAI more often. On my local system, InvokeAI runs much better with low VRAM, making it a great choice. The web UI of this project is also so beautifully modern. Where not being able to be more creative and transfering prompts from Automatic1111 web UI is a real bummer.

From own experience I can say, the increased tokens do **a lot**. It is notable that the tokens before the official limit do have a much heavier influence in Automatic1111 web UI. But later tokens are still considered, making it easier to be creative with more words. After like 3 or 4 * 77 prompt lengths though, there is no further effect in Automatic1111's implementation. So the limit cannot be endlessly stretched.

**Comment by mirrexagon** [comment] 2023-02-04 09:11
A cursory look suggests that the later actual implementation of unlimited tokens via concatenation was here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/2138
Not sure if it has changed since then.

Their wiki describes the unlimited token feature here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#infinite-prompt-length

>Typing past standard 75 tokens that Stable Diffusion usually accepts increases prompt size limit from 75 to 150. Typing past that increases prompt size further. This is done by breaking the prompt into chunks of 75 tokens, processing each independently using CLIP's Transformers neural network, and then concatenating the result before feeding into the next component of stable diffusion, the Unet.
>
>For example, a prompt with 120 tokens would be separated into two chunks: first with 75 tokens, second with 45. Both would be padded to 75 tokens and extended with start/end tokens to 77. After passing those two chunks though CLIP, we'll have two tensors with shape of `(1, 77, 768)`. Concatenating those results in `(1, 154, 768)` tensor that is then passed to Unet without issue.

It does sound similar to what NovelAI described in the blog post linked by feffy380 (https://blog.novelai.net/novelai-improvements-on-stable-diffusion-e10d38db82ac)

**Comment by n00mkrad** [comment] 2023-02-04 17:51
InvokeAI refuses to implement it because it's based on leaked NAI info.

**Comment by briankendall** [comment] 2023-02-09 17:07
After playing around with both InvokeAI and Automatic1111's web UI, I can say that the missing ability to handle longer prompts is the one major thing that prevents InvokeAI from being usable for me. Without that feature, I cannot properly get any work done in it. Too many of my prompts simply require more than 75 tokens, especially when using models that require comma separated tokens (as each comma itself is a token).

I tried manually specifying prompt blending myself, but the results I'm getting are simply not good. For whatever reason it seems like large portions of my prompt are simply being ignored. And while there may be something I'm doing wrong that I could correct, the cognitive load of having to manually break apart and maintain my prompt in different sections is simply _not_ something I want to nor should I have to deal with. Automatic1111's web UI simply handles it for me and does a great job. It's so effective that I think such a feature should be considered standard and a must-have for a proper stable diffusion interface. And from what I can tell, there are implementations of it now that don't directly stem from the NovelAI leak so I see no reason not to include it.

It's a shame, too, because I _vastly_ prefer the UI and workflow of InvokeAI. Its inpainting feature is killer. If it simply had the ability use longer than 75 token prompts then I would ditch the Automatic1111 UI in a heartbeat.

**Comment by hipsterusername** [comment] 2023-02-09 17:13
@damian0815 - Acknowledging that it’s effectively just a blend, what are your thoughts on alerting the user of truncated tokens and allowing them to run it with an “auto-blended” form of the prompt? I don’t want to become so opaque as to obscure what’s happening because I think that the blend approach is way less than ideal, but the “average” user may benefit

cc: @psychedelicious @blessedcoolant

**Comment by Neosettler** [comment] 2023-02-09 17:55
@briankendall allowing more then 77 tokens seems to be critical a critical move to make for users.

> InvokeAI refuses to implement it because it's based on leaked NAI info.

Sounds noble but does it have real weight in the big scheme of things? Find a way to make it legit and/or seek advise from a lawyer stand point if it helps you sleep better.

**Comment by n00mkrad** [comment] 2023-02-09 20:26
> Agreeing with @briankendall allowing more then 77 tokens seems to be a critical move to make for users.
> 
> > InvokeAI refuses to implement it because it's based on leaked NAI info.
> 
> Sounds noble but does it have real weight in the big scheme of things? Find a way to make it legit and/or seek advise from a lawyer stand point if it helps you sleep better.

I was just stating the facts, I don't give a shit if it was stolen info or not, I want this feature as much as everyone else in here.

**Comment by psychedelicious** [comment] 2023-02-09 20:49
It's not like invokeai doesn't want to support this, it's that the code was apparently lifted from a code base which does not have a license that allows us to do it. At least, the legal side of this is very vague and risky.

Also, we have been busy with a lot of other things and haven't given this the revisit it deserves.

After reading @briankendall 's feedback, it's clear that the token limit is a major hindrance to productivity.

Can anybody point us to an implementation which is from a properly licensed open source project?

Flagging @lstein for input on this.

**Comment by hipsterusername** [comment] 2023-02-09 21:24
> Sounds noble but does it have real weight in the big scheme of things? Find a way to make it legit and/or seek advise from a lawyer stand point if it helps you sleep better.

To be clear, it sounds like you're asking the question "Do ethical decisions have a real weight in the grand scheme of things?" In case this is news - Yes, they do. I'm as pragmatic a person as you can find, but even I recognize the difference between dealing with practical realities and excusing immoral behavior. There's no reason to lift stolen code when we can come up with something that works as good, or better. 

> Can anybody point us to an implementation which is from a properly licensed open source project?

@psychedelicious - I think we can work to implement our own, using blends and pads. It may be an experiment/science project, but at the very least we can do "something" with a prompt that would otherwise be truncated.

**Comment by ResidentChief** [comment] 2023-02-09 21:26
Surely the idea of cutting something up, proccessing it and putting the
results back together cant be copyrightable…

**Comment by fish-face** [comment] 2023-02-15 18:45
> Surely the idea of cutting something up, proccessing it and putting the results back together cant be copyrightable…

No, it isn't. Get someone to write the feature who hasn't seen any NovelAI code (or the A1111 code, to be safe) and there isn't an issue.

**Comment by hipsterusername** [comment] 2023-02-15 19:21
@damian0815 has already started exploring how this could be enabled without directly referencing their code, and he's shared positive results. Once we're confident we can implement this well (and or better), we will!

**Comment by briankendall** [comment] 2023-03-07 19:08
Any updates on this? I still miss using InvokeAI!

**Comment by damian0815** [comment] 2023-03-08 17:07
there's PR #2896 . please test if you're used to using longer prompts and post your experience on that PR - if it isn't working as intended ,please post the prompt you're using and what you expect it to do vs what it actually does.

**Comment by lstein** [comment] 2023-03-08 17:18
I have a broader question about whether bypassing the 77 token limit will actually improve results. I find that as prompts get longer there's a distinct sense of diminishing returns where previous well-tuned details start dropping out at random. Most of the textbook-length prompts that I see out there are voodoo concatenations of superlatives that are subject to the same stochastic variations in qualilty that short prompts have. 

If anyone has actually conducted a systematic study of long vs short prompt (e.g. using a randomized double-blind trial to judge how well the prompt and the image line up), please point me to it and I'll happily eat my words.

**Comment by lstein** [comment] 2023-03-08 17:21
That being said, I'll give @damian0815 's PR a spin and see.

**Comment by Neosettler** [comment] 2023-03-08 17:47
To jump on @lstein comment, it's all about control and sometimes it's not double the tokens that is necessary but a few could make a difference. In all cases, I'd suggest to make this feature optional, --extended_tokens. Also, having less than 77 tokens should result in the same output image if --extended_tokens is true or false.

**Comment by hipsterusername** [comment] 2023-03-08 22:39
> If anyone has actually conducted a systematic study of long vs short prompt (e.g. using a randomized double-blind trial to judge how well the prompt and the image line up), please point me to it and I'll happily eat my words.

@lstein - I would love to see this. Maybe we can get the discord community to be Guinea pigs 😜 - I tend to believe your intuition is right, fwiw

**Comment by psychedelicious** [comment] 2023-03-09 00:23
I my experience there is an optimal token count range. Too few and results are vague - too many and it becomes superstition. 

Negative conditioning seems like a thing where having infinite tokens could really help, but maybe that's a mistaken intuition.

**Comment by damian0815** [comment] 2023-03-09 12:08
> I my experience there is an optimal token count range. Too few and results are vague - too many and it becomes superstition.

the diffusion process has a fixed number of attention "heads" , almost 2x as many for SD2 as SD1, so that would make sense. on the other hand, there's only so much attention to go around - what is happening with longer prompts i think is that increasing amounts of the prompt are effectively ignored, and when people say "longer prompts do have an effect" the effect they're seeing is not that there is *more* detail rather that the attention heads are fixating on different parts of the prompt (and, because there is only a fixed number of them, ignoring different parts)

**Comment by lstein** [comment] 2023-03-09 14:15
I'm glad there is an objective explanation for these subjective
experiences. Is there a way to infer the maximum number of tokens that will
be paid attention to given the finite number of attention "heads"? Knowing
this value would make it easier for people to tune their prompts by
budgeting their token usage intentionally, rather than letting the system
stochastically ignore tokens it can't pay attention to.

**Comment by Neosettler** [comment] 2023-03-09 17:33
@lstein What about an instant feedback on tokens analyzer? 

Same as the token log but on demand. Something like: 
!tokenize [prompt] [negative]

**Comment by damian0815** [comment] 2023-03-09 19:20
> Is there a way to infer the maximum number of tokens that will be paid attention to given the finite number of attention "heads"?

@lstein i'm a little fuzzy on the details tbh, but my understanding is that there's no rigid logic that's doing this, it's just NN magic convoluting a fat 77x768 tensor against some sort of 77-wide activation tensor. (which is part of why i can't wrap my head around why >77 tokens even works)

**Comment by psychedelicious** [comment] 2023-03-09 20:02
Is attention value limited on my by the precision of the numbers used or is there a Planck length for attention?

**Comment by damian0815** [comment] 2023-03-09 20:24
dunno

**Comment by damian0815** [comment] 2023-03-09 20:27
oh we can close this issue i think. implemented in #2896

**Comment by v3ss0n** [comment] 2023-04-23 17:18
merged right?

**Comment by hipsterusername** [comment] 2023-04-23 17:29
> merged right?

It's merged into Main, but not "released" in a stable version yet.

**Comment by Neosettler** [comment] 2023-04-23 17:54
It is nice to see progress on this. Having backward compatibility in mind. Is there a way to turn this feature on/off? 

The reason I'm asking is that if previously generated images had tokens being discarded, using the same settings (from metadata) the result image would be completely different.

**Comment by Neosettler** [comment] 2023-04-24 15:25
very well, thank you for clarifying. see new request:
https://github.com/invoke-ai/InvokeAI/issues/3263

**Comment by schoenid** [comment] 2023-10-26 04:08
I changed completely to stable diffusion webui, because of that limit in InvokeAI. It's nearly impossible to create the images I want with only 77 tokens.

On the other side, I miss the stability of InvokeAI !!!

**Comment by schoenid** [comment] 2023-12-06 23:06
I'm getting more and more familiar with stable diffusion webui and I'm no more missing InvokeAI now.
In contrary, I'm happy I did this step. :)

**Comment by hipsterusername** [comment] 2024-02-21 15:52
Closing this, as the change was made prompts are appended. Any issues with this should be considered bugs.

**Closed by hipsterusername** 2024-02-21 15:52 UTC
Labels: enhancement

**Comment by mirh** [comment] 2024-04-20 23:46
Are `Token indices sequence length is longer than the specified maximum sequence length for this model (xx > 77). Running this sequence through the model will result in indexing errors` lines still supposed to appear in the terminal?
