### ISSUE TITLE
[enhancement]: Configurable Hotkeys

### ISSUE THREAD

**Issue by joshistoast** [invoke-ai/InvokeAI#5544] opened 2024-01-22 17:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I'd like for us to rework hotkeys to use a db or json file to store default hotkeys for ui actions, and a ui to edit them.

### Additional Content

Discussion originally started on #5542

**Comment by psychedelicious** [comment] 2024-01-24 00:02
Duplicate of #3959

**Closed by psychedelicious** 2024-01-24 00:02 UTC
Labels: enhancement
