### ISSUE TITLE
[bug]: Invoke downloads config.yaml after each restart

### ISSUE THREAD

**Issue by grunblatt-git** [invoke-ai/InvokeAI#6855] opened 2024-09-13 23:47 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

macOS

### GPU vendor

Apple Silicon (MPS)

### Version number

5.0.0.a5

### Browser

Chrome

### What happened

I ran into the following error when generating images while being disconnected from the internet

>[InvokeAI]::ERROR --> Error while invoking session <someUUID>, invocation <someUUID> (compel): HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1b05f72b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))

It seems to me that invoke cannot find the correct config.yaml for the model locally and tries to redownload it from huggingface after each reboot.

The models were imported through the model manager and saved the following "Path To Config" : ```stable-diffusion/v1-inference.yaml```

### What you expected to happen

Generating images should be possible without being connected to the internet

### Additional context

After generating a single image while being connected to the internet, inference runs flawlessly (even offline) until invoke is restarted.

**Comment by psychedelicious** [comment] 2024-09-14 09:28
Duplicate of #6623

**Closed by psychedelicious** 2024-09-14 09:28 UTC
Labels: bug
