### ISSUE TITLE
error when using arg --host 0.0.0.0 on M1

### ISSUE THREAD

**Issue by Vrk3ds** [invoke-ai/InvokeAI#926] opened 2022-10-04 22:17 UTC
**Describe your environment**
- GPU: [mps]
- VRAM: [64gb]
- CPU arch: [arm]
- OS: [macOS]
- Python: [miniconda]
- Branch: [Development]
- Commit: [run `git show` and paste the line that starts with "Merge" here]

**Describe the bug**
runs fine until I add the arg --host 0.0.0.0 to make it available from other systems on my network. then I get this error after trying to attach via the address:9090

http://10.0.0.120:9090 is not an accepted origin. (further occurrences of this error will be logged with level INFO)
ERROR:engineio.server:http://10.0.0.120:9090 is not an accepted origin. (further occurrences of this error will be logged with level INFO

Not sure if I am doing something wrong/dumb or if it really is a bug?

**Comment by psychedelicious** [comment] 2022-10-05 01:28
You need to add the server to the CORS allowed origins list e.g. `python scripts/dream.py —web —cors http://10.0.0.20:9090` if `http://10.0.0.20:9090/` is the address of the server on your local network.

**Comment by TheBrinkOfTomorrow** [comment] 2022-10-05 15:03
> 

I'm having exactly the same issue issue (Debian 11 (headless), release candidate 2.0.0 #930);  adding the --cors <server URL> arg doesn't seem to make any difference....

The web host has always worked perfectly for me until today when I switched to the RC branch and updated my pip dependencies...  I'll switch back to main and see if the issue goes away...
```
python3 ./scripts/dream.py  --outdir outputs/preflight --web --cors <server URL> --host 0.0.0.0
>> Started Invoke AI Web Server!
Point your browser at http://localhost:9090 or use the host's DNS name or IP address.
<server URL> is not an accepted origin. (further occurrences of this error will be logged with level INFO)"
```

**Comment by lstein** [comment] 2022-10-05 16:04
@psychedelicious, @blessedcoolant : Something's not right about this. We should not have to individually add the host's own IP address to the `--cors` list, should we?

From: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

> Cross-Origin Resource Sharing ([CORS](https://developer.mozilla.org/en-US/docs/Glossary/CORS)) is an [HTTP](https://developer.mozilla.org/en-US/docs/Glossary/HTTP)-header based mechanism that allows a server to indicate any [origins](https://developer.mozilla.org/en-US/docs/Glossary/Origin) (domain, scheme, or port) other than its own from which a browser should permit loading resources. CORS also relies on a mechanism by which browsers make a "preflight" request to the server hosting the cross-origin resource, in order to check that the server will permit the actual request. In that preflight, the browser sends headers that indicate the HTTP method and headers that will be used in the actual request.

In this case, the users are in the _same domain_ as the web server and the server should accept their requests. CORS should only kick in when a request is coming in from an unexpected domain. For example, I have to use it when I am crossing a firewall using an ssh proxy, and my browser is accessing the server through an unexpected route.

**Comment by psychedelicious** [comment] 2022-10-05 23:09
I've just checked out tag `2.0.0-rc3` and everything works as expected. Note that CORS is needed for socketio to work. 

Example: My server local IP is, at the moment, `172.20.10.3`. I specify `--host 0.0.0.0` without any CORS and browsing to `http://172.20.10.3:9090` does not work from any machine on the network; the page loads but socketio cannot connect. 

When I add `--cors http://172.20.10.3:9090` everything works both from the server and other machines on the same network. 

@TheBrinkOfTomorrow 
- When you load the URL in a web browser, does the page load but you get 'Disconnected' at the top right? This indicates the CORS address isn't correct, if so please double check
- Was it the new web UI that was previously working or the old one?

**Comment by TheBrinkOfTomorrow** [comment] 2022-10-06 00:57
> @TheBrinkOfTomorrow
> 
>     * When you load the URL in a web browser, does the page load but you get 'Disconnected' at the top right? This indicates the CORS address isn't correct, if so please double check
> 
>     * Was it the new web UI that was previously working or the old one?
Yes, the page loads, but disconnected in the top right... and 

It was the old web UI that was previously wotking (on multiple machines), and now the new UI isn't working on those same machines.

If I start with --host 0.0.0.0 then even the localhost  is not able to connect... e.g:
```
python3 scripts/dream.py --outdir outputs/preflight --web --web_verbose --host 0.0.0.0
....
>> Started Invoke AI Web Server!
Point your browser at http://localhost:9090 or use the host's DNS name or IP address.
LH-Tr6StAQQttQwnAAAA: Sending packet OPEN data {'sid': 'LH-Tr6StAQQttQwnAAAA', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 100000}
http://localhost:9090 is not an accepted origin. (further occurrences of this error will be logged with level INFO)
```
Starting with --cors http: doesn't make any difference.... still get "Disconnected" in top right and the following output:
```
python3 scripts/dream.py --outdir outputs/preflight --web --web_verbose --host 0.0.0.0 --cors http://localhost:9090/
...
>> Started Invoke AI Web Server!
Point your browser at http://localhost:9090 or use the host's DNS name or IP address.
qlqHbxoivZlb1shTAAAA: Sending packet OPEN data {'sid': 'qlqHbxoivZlb1shTAAAA', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 100000}
http://localhost:9090 is not an accepted origin. (further occurrences of this error will be logged with level INFO)
```
I've replicated the same behaviour using Debian 11 and Ubuntu 20.04 to run dream.py (on two different machines), and using Firefox (locally and remote) and Safari (remote; macOS and iOS) as the browser...

**Comment by TheBrinkOfTomorrow** [comment] 2022-10-06 01:13
Yes, the page loads, but shows "Disconnected" in the top right and page is non-functional. With errors in the server output.
It was the old web UI that was previously working (on multiple machines), and the new UI isn't working on those same machines.

I've realized the problem at my end - it was my mistake - I was adding a trailing slash ('/') to the server url at the end of the --cors argument.... this prevents it working... (maybe that could be filtered out when you parse the cli args?).

i.e.: "python3 scripts/dream.py --outdir outputs/preflight --web --web_verbose --host 0.0.0.0 --cors http://myserver-ip:9090/" does not work (even with localhost)... but removing the trailing slash does ("--cors http://myserver-ip:9090")

**Comment by psychedelicious** [comment] 2022-10-06 02:37
Thanks @TheBrinkOfTomorrow, glad it is working. 

I don't think we will add any kind of error checking because this as this is exactly how cors should work, and we defer to the mature server package (flask) to handle error cases.

**Comment by psychedelicious** [comment] 2022-10-06 08:08
@Vrk3ds can you please confirm that the issue is resolved by adding the cors origin?

**Comment by Vrk3ds** [comment] 2022-10-06 12:00
> @Vrk3ds can you please confirm that the issue is resolved by adding the cors origin?

Yea when I add the —cors argument it works as expected .

is that documented somewhere for other who May experience the same issue?

**Comment by psychedelicious** [comment] 2022-10-06 13:57
Don't think it's documented anywhere, but it oughta be. We'll get it added.

**Closed by psychedelicious** 2022-10-06 13:57 UTC
Labels: bug
