### ISSUE TITLE
[bug]: Deleted Images not removed from web gui

### ISSUE THREAD

**Issue by mickr777** [invoke-ai/InvokeAI#1296] opened 2022-10-29 23:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12gb

### What happened?

When using the web gui deleted images are not removed from gui, however refreshing the page they are removed

web ui console show Disconnected from server as soon as the image is deleted, followed by Loaded 0 images

no errors are showing from the command line

### Additional context

Same issue On Chrome on windows/android, Microsoft edge on windows and Firefox on linux

**Comment by mickr777** [comment] 2022-10-29 23:04
looks like Fortyseven reported the bug as I was writing out my report, so sorry for double report

**Comment by hipsterusername** [comment] 2022-10-30 02:40
Marking duplicate of #1295

**Closed by hipsterusername** 2022-10-30 02:40 UTC
Labels: bug
