### ISSUE TITLE
Generation with k_samplers uses `steps - 1` instead of `steps`

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#900] opened 2022-10-03 21:01 UTC
**Describe your environment**
- GPU: mps
- VRAM: 32
- CPU arch: arm
- OS: macos
- Python: [Anaconda/miniconda/miniforge/pyenv/other (explain)]
- Branch: development
- Commit: introduced in 958d7650dd249b37df49036ae91a40739008a7f8

**Describe the bug**
Generation with k_samplers uses `steps - 1` instead of `steps`. Does not affect DDIM or PLMS.

<img width="603" alt="Screen Shot 2022-10-04 at 08 01 16" src="https://user-images.githubusercontent.com/4822129/193681739-dd26fbcd-c824-441b-b297-d5ba58667baa.png">

**Comment by psychedelicious** [comment] 2022-10-03 21:03
@lstein Think this one is a job for you - hopefully a nice, clean, obvious off-by-one error 😛

**Comment by lstein** [comment] 2022-10-03 21:33
I'm aware of it, but the issue is that the k* samplers **always** had the off-by-one error. They just didn't show it in the tqdm display! The thing about the k* samplers is that they have a noise schedule with an operation that looks like this:

~~~~
updated_value = function(noise[step],noise[step+1])
~~~~

So when you loop, you loop from `0` to `total_steps-1`. If you looked carefully at the earlier implementation, the tqdm actually started at 1 and counted upwards.

So I can restore the previous cosmetic behavior, or I can do a full total_steps, but the results won't be the same as previous. Which is preferable?

**Comment by psychedelicious** [comment] 2022-10-03 21:50
I don't understand the inner workings of the noise schedule and such, but I do know that when we ask for 20 steps and it shows we got 20 steps, we get a comfy warm feeling. But apparently getting 19 steps makes us think something is wrong.

Particularly: programmers, who not familiar with the inherent off-by-one error of the k* samplers, may experience flashbacks to past traumatic debugging sessions. This is what I experienced.

- Are DDIM and PLMS samplers actually doing one more step than the k* samplers? Does it even make sense to compare them like that? 
- Do other implementations have this same off-by-one error and they just hide it from the user?

**Comment by lstein** [comment] 2022-10-03 22:19
I'm just going to make it do exactly the number of steps we ask it to do. I'll consider the previous behavior a bug.

Also, come to think of it, we're using a different noise schedule now (since the last PR) and the results won't be comparable to previous generations.

**Comment by Birch-san** [comment] 2022-10-04 22:49
https://github.com/crowsonkb/k-diffusion/blob/567e11f7062ba20ae32b5a8cd07fb0fc4b9410cf/k_diffusion/sampling.py#L93

the k-samplers sample _pairwise_. on each step: they consult `sigmas[i]` **and** `sigmas[i+1]`. hence they iterate only as far as the _penultimate_ sigma, to be sure that there is always a `sigmas[i+1]` ahead of them.

**Comment by Birch-san** [comment] 2022-10-04 22:55
when they reach the final iteration in the loop (i.e. sampling the penultimate and final sigma): there is a special-case; they do not bother asking the model to provide a denoising prediction for timestep 0:  
https://github.com/crowsonkb/k-diffusion/blob/567e11f7062ba20ae32b5a8cd07fb0fc4b9410cf/k_diffusion/sampling.py#L110  
it wouldn't make sense for two reasons (second is the more important one):  
- LatentDiffusion is a DDPM-based (i.e. _discrete_) diffusion model, which was only trained on [the following sigmas](https://gist.github.com/Birch-san/6cd1574e51871a5e2b88d59f0f3d4fd3) -- note that the smallest is 0.0292; it was never trained on 0
- there's no point asking "assuming this image has 0 noise: what do you think this image will look like if I remove all the noise from it"

**Comment by lstein** [comment] 2022-10-04 22:56
This PR is rendered moot by #925 and I'm going to close it in order to avoid any further craziness.

**Closed by lstein** 2022-10-04 22:56 UTC

**Comment by psychedelicious** [comment] 2022-10-04 23:36
@Birch-san thank you for the explanation senpai
