### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by Neosettler** [invoke-ai/InvokeAI#982] opened 2022-10-07 21:12 UTC
Hello,

In the spirit on using Python only (no Conda or else) to install the repo dependencies, here is what I have so far:

install git
cd F:\
git clone https://github.com/lstein/stable-diffusion.git

install python + add system env
create virtual environment: python - venv F:/stable-diffusion/envs/ldm
F:/stable-diffusion/envs/ldm/Scripts/activate
python -m pip install --upgrade pip

pip install -r \stable-diffusion\requirements-win.txt:
ERROR: file:/// (from -r F:\stable-diffusion\requirements-win.txt (line 33)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

when removing line 33, it goes through and I can use dream.py (no upscale or face restore) ! What will be miss there?

Now when comparing with a Conda setup, there is no "src" folder being created with source code. is that related to line 33?

Could someone help with this?

python F:\stable-diffusion\scripts\preload_models.py does seems to do much...

**Comment by Neosettler** [comment] 2022-10-07 23:06
adding realesrgan==0.3.0 to equirements-win.txt seems to do the trick. Proof that Conda can be exorcised, at least on Windows.

**Comment by tildebyte** [comment] 2022-10-09 16:22
For one thing, `pip install -r \stable-diffusion\requirements-win.txt` shouldn't work (it's actually wrong); you need to be **in the repo directory**: `cd stable-diffusion; pip install -r ./requirements-win.txt`

Also, you should probably switch to `git clone https://invoke-ai/InvokeAI`

**Comment by Neosettler** [comment] 2022-10-09 18:52
Thank you for your advice tildebyte, in the spirit of having a portable InvokeAI api, the venv technic does not work either. I'm now trying with [winpython](https://winpython.github.io/). Any support with this endeavor would be greatly appreciated.

**Comment by tildebyte** [comment] 2022-10-09 20:37
@Neosettler;

> venv technic does not work either

What **specifically** doe this mean?

**Comment by Neosettler** [comment] 2022-10-09 20:52
Still, having InvokeAI being portable in mind, as I understand it, venv requires to have Python installed. So, the process in itself is flawed from the get-go. Let's say, having Python installed is a lesser evil, creating a venv adds a config file that targets where Python is installed, by default, Python resides under the user directory. Thus, copying the root folder to another machine will result in a broken Python path unless the users are identical on both system.

**Comment by Neosettler** [comment] 2022-10-09 20:59
Even using winPython doesn't allow copying the root directory and work on another PC either. Something seems to be caught up using hidden resources, path, environment variables or alike somewhere down the pipes. Been trying to solve this for several days now but no luck so far. There's always a module or another that cant be found when launching dream.py.

**Comment by tildebyte** [comment] 2022-10-09 22:18
Python is required no matter what.

Python installations vary by

- location per version (mostly for very old Pythons on Windows, but still)
- location DEFINITELY per-platform (various Linux distros put it all over the place)

Python MUST be "installed" (for varying definitions of "installed" per-platform). Trying to bundle up Python itself on one system and move it to another is a fool's errand.

Having said all of that, bundling up a Python *application* (like InvokeAI) into a portable virtual environment **without** Python *should* be possible.

P.S. I lied a little. It *is* possible to make an executable application out of a Python source repo, but it is

- not easy
- there's no standard
- one has to (not unsurprisingly) create a separate app for each supported platform
- out of scope for this repo at this time (we can't even settle on conda vs. pip)

**Comment by Lostdragon5** [comment] 2022-10-10 22:43
I've tried installing on windows 3 different times now, twice using pip in the command line and once using the notebook, and all of them have given me this same error:

> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\_[My Name]_\\AppData\\Local\\Temp\\pip-install-wbl23oma\\basicsr_967a9d1793c44c09837596429a96019a\\.eggs\\torch-1.12.1-py3.10-win-amd64.egg\\caffe2\\python\\serialized_test\\data\\operator_test\\learning_rate_adaption_op_test.test_learning_rate_adaption_op_normalization.zip'

I'm gonna try once more with anaconda, but I have funny feeling I'm gonna get the same error there as well, or at least a similar one.

**Comment by tildebyte** [comment] 2022-10-10 23:16
Several people have seen this - I don't understand it at all, and can't reproduce. Very frustrating.

**Comment by Lostdragon5** [comment] 2022-10-11 01:31
Worst part is that I've never gotten that specific error before, but it seems virtually all Distributions of Stable Diffusion have some sort of major issue when installing on my computer, and it's always different with each one.

After a few hours I got it to install with Anaconda (which was much more straightforward ironically), but now it keeps trying to launch `Using more accurate float32 precision` which uses too much VRAM, and my normal fix isn't working... Ugh.

**Comment by Neosettler** [comment] 2022-10-16 16:40
I agree with you [tildebyte](https://github.com/tildebyte), it is not easy. It's one of those thing that you MUST want to have it for it to come to realty. I'm positive that it is possible to have a portable Python (on Windows that is) without installing anything and mingle with the user's OS. My best guess is that it should be done via a batch file, something around those line,

if not defined PYTHON (set PYTHON=python)
if not defined VENV_DIR (set VENV_DIR=venv)
set PYTHON="%~dp0\python\Python.exe"

Some obscured ALL in Japanese packaged SD does it with the lines above.

"Dryland is not a myth, I've seen it!" Kevin Costner.

**Comment by tildebyte** [comment] 2022-10-16 17:40
@Neosettler; We have a contributor who has a "one-click" installer which will remove Conda completely and be relatively portable (although frankly, users are *much* better off installing Python and using virtual environments, at least for *this* repo at its current state of development)

**Comment by Neosettler** [comment] 2022-10-16 22:02
Thank you for your suggestion [tildebyte](https://github.com/tildebyte). Make no mistake about this, having 1 or 100 steps installer makes no difference. The portable idea is not as much about step count it is about not to tempered with the user's OS. Imho, empowering artist and dev to focus on productivity instead of trouble shooting the installation/update process is the main goal.

**Closed** 2023-04-02 16:35 UTC
Labels: bug, install
