### ISSUE TITLE
Tracker for breaking bugs in new webUI

### ISSUE THREAD

**Issue by tildebyte** [invoke-ai/InvokeAI#619] opened 2022-09-16 18:09 UTC
@lstein, @psychedelicious, @Kyle0654, @netsvetaev (apologies if I missed anyone)

**Describe your environment**
These bugs should occur on any platform

**Describe the bug**
1. Reproducer: ` python backend/server.py`

```python
Traceback (most recent call last):
  File "C:\Users\quaestor\Source\stable-diffusion-stable\backend\server.py", line 22, in <module>
    from ldm.dream.pngwriter import PngWriter, PromptFormatter
ImportError: cannot import name 'PromptFormatter' from 'ldm.dream.pngwriter' (c:\users\quaestor\source\stable-diffusion-stable\ldm\dream\pngwriter.py)
```

2. Reproducer: attempt to generate an image

```python
Traceback (most recent call last):
  File "C:\Users\quaestor\Source\stable-diffusion-stable\backend\server.py", line 375, in generate_images
    model.prompt2image(
  File "c:\users\quaestor\source\stable-diffusion-stable\ldm\generate.py", line 344, in prompt2image
    results = generator.generate(
  File "c:\users\quaestor\source\stable-diffusion-stable\ldm\dream\generator\base.py", line 73, in generate
    image_callback(image, seed)
  File "C:\Users\quaestor\Source\stable-diffusion-stable\backend\server.py", line 364, in image_done
    path = save_image(image, all_parameters, result_path, postprocessing=postprocessing)
  File "C:\Users\quaestor\Source\stable-diffusion-stable\backend\server.py", line 310, in save_image
    path = pngwriter.save_image_and_prompt_to_png(image, command, filename)
TypeError: PngWriter.save_image_and_prompt_to_png() missing 1 required positional argument: 'name'
```

**Additional context**
This is a tracker for bugs relating to the recent web UI work. Obviously it is under heavy development, so this is not high-priority work.

**Comment by Kyle0654** [comment] 2022-09-16 18:50
I have a PR https://github.com/lstein/stable-diffusion/pull/602 that should replace server.py. Can you please test against that and see if it works? https://github.com/Kyle0654/lstein-stable-diffusion/tree/api-server

```
python server/application.py --host 0.0.0.0
```

**Comment by lstein** [comment] 2022-09-16 18:58
There are a small number of problems caused by my reworking of the metadata written to PNG files. Hopefully PR #602 will fix, but if not I'll be fixing the problems I created later this afternoon.

**Comment by Kyle0654** [comment] 2022-09-16 19:00
My PR will still write metadata to the `Dream` field right now. Can change that though if you'd like (just comment on the PR 🙂).

**Comment by lstein** [comment] 2022-09-16 19:02
I think we should be reading and writing from the JSON-formatted "sd-metadata" field.

Sadly have to go pick up my kids at school now. Will be offline for an hour. Haste makes waste!

**Comment by Kyle0654** [comment] 2022-09-16 19:03
Haha I mean I have work all day so no rush =P

**Comment by psychedelicious** [comment] 2022-09-16 19:34
> I have a PR #602 that should replace server.py. Can you please test against that and see if it works? https://github.com/Kyle0654/lstein-stable-diffusion/tree/api-server

I think there is some confusion, I named my server script `server.py` - same as the existing script - but its in a different directory `backend/`.

The bugs in this thread are for my `server.py`

**Comment by lstein** [comment] 2022-09-16 19:41
Meanwhile I’ll fix the DREAM prompts. There was a “minor” user requested change which broke our parser.

**Comment by lstein** [comment] 2022-09-16 19:45
Just to clarify. The old server launched with dream.py —web should still be working. If not, open a new issue. 

My apologies to @psychedelicious and @Kyle0654 for messing up what should have been a smooth roll out.

**Comment by lstein** [comment] 2022-09-16 20:38
I just merged in PR #602 , which fixes the immediate crashes. I see @psychedelicious has another PR, which I will check out.
I'm a bit under the gun because my HPC goes into an annual two-day "maintenance window" in about an hour, and I won't be able to do any more development or testing until Monday. This is part of the reason I was inexcusably hasty today!

**Comment by psychedelicious** [comment] 2022-09-16 20:45
I borked my original PR, whoops. Here is an un-borked one #624

**Comment by lstein** [comment] 2022-09-16 20:59
Ok. Merged with development. Immediate problems solved I think.
Now I've got to try to reconstruct my environment on an alternative server that forbids conda. Sigh.

**Comment by psychedelicious** [comment] 2022-09-16 21:11
Yep immediate problems solved from my testing the up-to-date development branch. Cool!

Good luck @lstein - the python venv landscape is just about as intelligible as the modern javascript "ecosystem" - not very! I take it you are not so willing to take a couple days off while the maintenance proceeds?

**Comment by lstein** [comment] 2022-09-16 22:00
I may have to! I was looking forward to doing more code cleanup and working on pipelining the postprocessing steps, but instead I'll have to spend time with my wife and kids.

I'm in venv/cmake/pip hell right now. It doesn't look good.

**Comment by Kyle0654** [comment] 2022-09-16 22:34
I noticed you restored the static files to the old version. Was the new stuff not working? I'll have no interface without those =(. Would it be alright if I replaced the old server with code to run the new backend? I don't know React at all, so having that simple interface to iterate on API features with has been super helpful.

**Comment by lstein** [comment] 2022-09-17 05:50
Oh god. I didn't realize you were reusing the same static file directory that the old web server was using. Because the PR didn't disable the old server, and everything else from the flask/react server was self-contained, I assumed you were generating the static content elsewhere. Also @psychedelicious mentioned in one of the comments that he had inadvertently replaced the static files, so I thought this was OK.

Anyway, easy enough to revert!

**Comment by lstein** [comment] 2022-09-17 05:54
There's a reference to config.js in index.html, but it's not in your PR #602. Is this intentional?

**Comment by lstein** [comment] 2022-09-17 06:04
Ok, the static files have been reverted.

**Comment by Kyle0654** [comment] 2022-09-17 06:05
No worries, I'm working on cleaning up the entrypoints right now. I'm also trying to get the console app using the same components so we can reduce duplicated code as much as possible =).

**Comment by psychedelicious** [comment] 2022-09-17 06:51
I've zhuzhed up the frontend code in #638. This is a first pass general tidy, mainly of the components. The next task is to tidy the internal state management. I want to ensure that is coherent and sensible before migrating to the new API.

**Comment by Kyle0654** [comment] 2022-09-17 08:52
@lstein I got rid of the old server.py and started trying to migrate the console prompt to use the same backend. I'm having a lot of trouble with the arg parser though - it seems to be getting rid of outdir (at least). I'm tempted to just move the grid stuff into the services, since it's the only thing having trouble, but it would also really benefit from waiting until a processing pipeline is complete (which I wasn't up to building tonight).

Take a look and let me know if you have any ideas: https://github.com/lstein/stable-diffusion/pull/640

**Comment by psychedelicious** [comment] 2022-09-17 09:02
I've just commented in #266 regarding grids. I don't think image grids have any business being in the backend. If you want a grid of images, maybe the client can do that for you, maybe you just use an image editor. Suggest we move the burden of support for grids to the client.

**Comment by smoke2007** [comment] 2022-09-17 12:38
not a bug, but I find myself continiously creating new lines in the prompt window when I want to start generating, because return/enter isn't mapped to launch "generate"

**Comment by smoke2007** [comment] 2022-09-17 12:49
Pressing Upscale on an already generated image hangs and terminal output =

`Traceback (most recent call last):
  File "J:\miniconda\envs\ldm\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "J:\miniconda\envs\ldm\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "J:\miniconda\envs\ldm\lib\site-packages\socketio\server.py", line 730, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "J:\miniconda\envs\ldm\lib\site-packages\socketio\server.py", line 755, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "J:\miniconda\envs\ldm\lib\site-packages\flask_socketio\__init__.py", line 282, in _handler
    return self._handle_event(handler, message, namespace, sid,
  File "J:\miniconda\envs\ldm\lib\site-packages\flask_socketio\__init__.py", line 826, in _handle_event
    ret = handler(*args)
  File "J:\stable2\stable-diffusion\backend\server.py", line 178, in handle_run_esrgan_event
    image = real_esrgan_upscale(
  File "j:\stable2\stable-diffusion\ldm\gfpgan\gfpgan_tools.py", line 150, in real_esrgan_upscale
    output, img_mode = upsampler.enhance(
UnboundLocalError: local variable 'upsampler' referenced before assignment`

**Comment by psychedelicious** [comment] 2022-09-17 20:14
@smoke2007 thanks, this will be changed so that Enter submits, but Shift+Enter still creates a new line.

**Comment by smoke2007** [comment] 2022-09-18 15:59
Also not sure if it's just me and it may be after my latest pull, not sure. But the progress bar in the UI up top goes about twice as fast ad the progress bar in the terminal, so it's at 100% when the terminal is only at 60% or so and the image isn't finished yet, sothe interface waits till terminal catches up and than the image appears.

**Comment by pbaylies** [comment] 2022-09-20 21:54
@psychedelicious looks like textual inversion is broken in the new WebUI, like the * token no longer works in the prompt? Tested on the `development` branch, running it like this:
`python backend/server.py --web --host 0.0.0 --embedding_path file.pt`

**Comment by psychedelicious** [comment] 2022-09-20 22:17
Hi @pbaylies , you are correct, this is not working at all, in fact the new UI server doesn't even accept any flags like you are giving it yet. Also, I didn't know this repo handles textual inversion, cool!

Can you provide an example textual inversion file for testing if there isn't one in the repo already that I have missed? Thanks.

**Comment by pbaylies** [comment] 2022-09-20 22:30
@psychedelicious Sure, here's one of me (pt files are .zip but rename to .pt first I guess, don't unzip)
[peter-pt.zip](https://github.com/invoke-ai/InvokeAI/files/9611606/peter-pt.zip)

**Comment by psychedelicious** [comment] 2022-09-20 22:45
@pbaylies Thanks. 
- I suppose the `*` token is defined in that file? 
- What should I expect to change in the generated images if I use it?
- Does it make sense to have an area in the UI dedicated to uploading (i.e. copying a `pt` to a dedicated folder inside the cloned repo) and managing/selecting `pt` files?

**Comment by pbaylies** [comment] 2022-09-20 22:48
Try the old web UI with a prompt like `a photo of *` and compare that against say `a photo of man`.
Tagging @lstein here for your other questions, I think it'd be nice to have some notation with different tokens supported / multiple embeddings, not sure if that is a thing or if there's a roadmap.

**Comment by Kyle0654** [comment] 2022-09-20 22:51
> I think it'd be nice to have some notation with different tokens supported / multiple embeddings, not sure if that is a thing or if there's a roadmap.

You can combine embeddings with different tokens already: https://github.com/invoke-ai/InvokeAI/blob/main/docs/features/TEXTUAL_INVERSION.md (near the very bottom)

It'd be nice to have some UI to manage the embeddings though =)

**Comment by psychedelicious** [comment] 2022-09-20 23:14
@pbaylies I mean, as a user of the UI, would you like to have some UI elements to handle the embeddings used or, with the way you use texxtual inversion embeddings, does it make more sense to have it as a command line flag? I'm guessing it's nice to have in the UI.

**Comment by pbaylies** [comment] 2022-09-21 01:28
> @pbaylies I mean, as a user of the UI, would you like to have some UI elements to handle the embeddings used or, with the way you use texxtual inversion embeddings, does it make more sense to have it as a command line flag? I'm guessing it's nice to have in the UI.

Yes, it'd be nice, given that there's no UI for it. Not necessary but a nice to have feature.

**Comment by pbaylies** [comment] 2022-09-21 01:31
> > I think it'd be nice to have some notation with different tokens supported / multiple embeddings, not sure if that is a thing or if there's a roadmap.
> 
> You can combine embeddings with different tokens already: https://github.com/invoke-ai/InvokeAI/blob/main/docs/features/TEXTUAL_INVERSION.md (near the very bottom)
> 
> It'd be nice to have some UI to manage the embeddings though =)

Yes, but can you use two different embeddings at once, in one prompt?

**Comment by Kyle0654** [comment] 2022-09-21 01:33
I'd like UI to manage the currently loaded model too ☺️

**Comment by psychedelicious** [comment] 2022-09-21 14:53
@pbaylies #732 adds support for textual inversion generated embeddings, thanks for bringing that to my attention and providing the test file.

**Comment by psychedelicious** [comment] 2022-10-20 12:32
There may be a few unaddressed bits and pieces in here, but I am going to close this as resolved as we are far past this version of the web UI.

**Closed by psychedelicious** 2022-10-20 12:32 UTC
Labels: bug
