### ISSUE TITLE
[enhancement]: Controlnet "Openpose refiner" / Openpose editor

### ISSUE THREAD

**Issue by suonnon** [invoke-ai/InvokeAI#5596] opened 2024-01-29 06:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Sometimes, the openpose does not detect the correct anatomy of the person in the photo, I'd love to see an openpose editor that embed inside the controlnet section. That's could help user correct the anatomy of the openpose more accurately. 🙏

**Comment by Millu** [comment] 2024-01-29 15:14
Agreed, this would be great! Closing this on as it's a duplicate of #5444 however

**Closed by Millu** 2024-01-29 15:14 UTC
Labels: enhancement
