### ISSUE TITLE
[bug]: invokeai-model-install.py restore script to vr 4  and 1 bug in run invokeai-web.py 

### ISSUE THREAD

**Issue by wolfkingal2000** [invoke-ai/InvokeAI#6042] opened 2024-03-23 23:25 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU VRAM

15

### Version number

v4.0.0rc5

### Browser

opera gx

### What happened

 r"invokeai-model-install.py." I've checked the latest version, but it seems to have been removed. can restored back Since I use Colab, it was very useful.
Could you provide any guidance on using new [v4.0.0rc4]and v4.0.0rc5 installation i installed but dont find invokeai.yaml file ? Thank you.

and for [v4.0.0rc4] and v4.0.0rc5  when run invokeai-web.py give this error can tell me what is problem

Traceback (most recent call last): File "/usr/local/bin/invokeai-web", line 8, in sys.exit(run_app()) File "/content/InvokeAI/invokeai/app/run_app.py", line 10, in run_app from invokeai.app.api_app import invoke_api File "/content/InvokeAI/invokeai/app/api_app.py", line 19, in from torch.backends.mps import is_available as is_mps_available File "/usr/local/lib/python3.10/dist-packages/torch/init.py", line 237, in from torch._C import * # noqa: F403 ImportError: /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so: undefined symbol: ncclCommRegister http (80)

### What you expected to happen

Traceback (most recent call last): File "/usr/local/bin/invokeai-web", line 8, in sys.exit(run_app()) File "/content/InvokeAI/invokeai/app/run_app.py", line 10, in run_app from invokeai.app.api_app import invoke_api File "/content/InvokeAI/invokeai/app/api_app.py", line 19, in from torch.backends.mps import is_available as is_mps_available File "/usr/local/lib/python3.10/dist-packages/torch/init.py", line 237, in from torch._C import * # noqa: F403 ImportError: /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so: undefined symbol: ncclCommRegister http (80)

**Comment by psychedelicious** [comment] 2024-03-25 07:21
We can't provide support for running the application on google colab. As far as I understand, this is actually against the terms of service for colab.

That said, it looks like you may be using an unsupported version of torch, or the colab server has some incompatible version of certain torch/nvidia packages installed.

I'm going to close this as nofix. If you can reproduce the issue on a computer that you have control over, we can troubleshoot, but we can't help with colab.

Regarding the other questions in this issue:
- To install models, use the model manager tab. We don't have plans to restore the `invokeai-model-install.py` script.
- The `invokeai.yaml` file is created when you start the application.

**Closed by psychedelicious** 2024-03-25 07:21 UTC
Labels: bug
