### ISSUE TITLE
[enhancement]: AnimateDiff support

### ISSUE THREAD

**Issue by vrubzov1957** [invoke-ai/InvokeAI#4731] opened 2023-09-28 16:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Ability to create animation with AnimateDiff or with same technology

### Alternatives

AnimateDiff extension for Automatic1111

**Comment by Millu** [comment] 2023-09-29 00:25
Agreed, would be awesome! 

Closing this as it's a duplicate of #4477

**Closed by Millu** 2023-09-29 00:25 UTC
Labels: enhancement
