### ISSUE TITLE
Multiple «copies» of images in the gallery appear

### ISSUE THREAD

**Issue by netsvetaev** [invoke-ai/InvokeAI#1085] opened 2022-10-13 13:01 UTC
mbp m1 2021
development branch

**Describe the bug**
Several copies of images appears in 3-4 hours without my actions. Maybe caused by minimizing/changing windows, but I’m not sure.

**To Reproduce**
Just wait, change the windows, in other’s case «Can reproduce this if I click "Load More" in the gallery multiple times quickly». 
Another report says «I noticed this if I load the page from a second computer, the first computer will show doubles in the gallery. And triples if I reload the other computer, etc».

Can be fixed by refreshing.

**Screenshots**
![image](https://user-images.githubusercontent.com/83028930/195603231-53a0460d-6f97-49ae-8187-b9318aaaf199.png)

**Comment by 19wolf** [comment] 2022-10-13 13:07
I can reproduce this by opening the web ui in multiple tabs or computers. The first tab will immediately duplicate all images when they're loaded by the new instance.

I think what may be happening is the call to load the images is happening on the server rather than in the browser? But I don't know how any of that works.

**Comment by psychedelicious** [comment] 2022-10-13 21:56
Ah, I think this is because we haven't implemented user specific sessions in the server. When a request to load images is sent, the server responds with a "broadcast" kind of message with the updated images.

**Comment by psychedelicious** [comment] 2022-10-19 23:17
An easy solution is to check if the image already exists in the gallery and if so, don't add it. I'll get this fixed soon.

**Comment by psychedelicious** [comment] 2022-10-19 23:50
Resolved in #1171

**Comment by psychedelicious** [comment] 2022-10-21 09:09
PR with fix is merged; closing.

**Closed by psychedelicious** 2022-10-21 09:09 UTC
Labels: bug
