### ISSUE TITLE
[bug] Prompt parser fails with improperly nested parentheses

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#1367] opened 2022-11-04 01:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### What happened?

Branch (as of about 4 hours before this bug was created)
`On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean`

Error: `Server error: Expected {conjunction | implicit_conjunction}, found ')' (at char 462), (line:1, col:463)`

With prompt: `photorealistic oil painting ((Full Frame)) of ((stunningly attractive)) ((Queen)), with very (Large cleavage ), ((full body)) ((perfect natural, 36DD Breast)) ((looking at the viewer))  high quality ((seductive look)),  highly detailed, ((((front posing view)))), ((space overhead)), (realistic breast physics), (perfect femenine face) (adorable), ((Looking at the Viewer)), ((Black eyes)), ((pure delicate innocent face)), (((High detailed face))), (((hyper realistic))), ((high detailed eyes)) [((half-frame))], ((redhead)),( digital Painting)) ((symmetrical voluptuous body)), ((300 ppi)), ((wide hip)), (thick thighs), sharp focus, intense, (((8k))), intricate details, art by ((Artgerm)), Greg Rutkowski, ((Oliver Valsecchi)), Maya Model, Detailed Render`

Another with the same error for user: `Ultra realistic oil painting ((Full Frame)) portrait of ((stunningly attractive)) ,(Woman) (((princess))), wearing (full fly open red kimono),( Golden color armor plate), (Detailed Kimono decoration),sitting on a ((throne), ((full curvy body)), ((Medium Breasts)),((cleavage)), Dramatic pose, ((((front view)))), ((space overhead)), (realistic breast physics), (perfect feminine face) (adorable), ((Looking at the Viewer)), ((Deep Blue eyes)), ((pure delicate innocent face)), (((High detailed face))), (((hyper realistic))), ((beautiful detailed eyes)) [((half-frame))], ((brown hair)),( digital Painting)) ((symmetrical voluptuous body)), ((wide hip)), (thick thighs), sharp focus, intense, (((8k))), intricate details, art by (Albert Lynch), Nekro, ((Marco Grassi)), ((artgerm)) and greg rutkowski, alphonse mucha, Detailed Render`

Posting on behalf of discord user "🅶🅻 ZAK Gurbawi".

### Contact Details

🅶🅻 ZAK Gurbawi

**Comment by psychedelicious** [comment] 2022-11-04 01:45
@damian0815 I cannot recreate this but the user can.

**Comment by psychedelicious** [comment] 2022-11-04 01:52
Full error:
![image](https://user-images.githubusercontent.com/4822129/199868060-31448165-f136-4bdd-b3bf-e11d15bb79c7.png)

**Comment by mickr777** [comment] 2022-11-04 03:13
> @damian0815 I cannot recreate this but the user can.

I can reproduce it appears the ( digital Painting)) is missing a leading (

**Comment by lstein** [comment] 2022-11-04 04:04
It’s an understandable user error. Is it possible to make the error message more informative do that the user knows where to look?

**Comment by psychedelicious** [comment] 2022-11-04 05:59
This is something for the backend to handle. E.g. the parser should default to handling this as a raw string if it has a problem parsing it. I believe Damian is working on improving the situation.

As a side-note, this is why we didn't go wiht nested parens... This prompt is used by some discord bot somewhere, user just trying it on invoke.

**Comment by damian0815** [comment] 2022-11-04 08:09
i cannot reproduce this on current development, but i can on main.

**Comment by damian0815** [comment] 2022-11-04 08:11
this is fixed in `e554c2607f00a5e51c03052acb9861ff21ec1c12` which is in development but not (yet?) in main

**Comment by lstein** [comment] 2022-11-10 21:34
The fix will appear with release 2.1.3, expected very soon.

**Closed** 2022-11-23 00:24 UTC
Labels: bug
