### ISSUE TITLE
Treshold and Perlin noise are not working as described

### ISSUE THREAD

**Issue by ioma8** [invoke-ai/InvokeAI#955] opened 2022-10-06 17:17 UTC
**Describe your environment**
- GPU: mps
- CPU arch: arm
- OS: macOO
- Branch: development
- Commit: c7ccb9dacd35d2195315b079af84b772e6782f47

**Describe the bug**
According to the documentation, the Treshold value should (using k_euler_a sampler) prevent the oversaturation on higher CFG values. However when I set 0 or 50 as value for treshold through the web UI it produces the exact, oversaturated image.

Bug no. 2: setting the Perlin noise to non-zero value changes the generated image. But it is not dependent on the value. Same image is produced whether I use 0.2 or 0.5 or 0.8 value.

**Screenshots**
<img width="1504" alt="image" src="https://user-images.githubusercontent.com/6624752/194376904-5311939d-50d2-4031-b9c7-d46cc9748c22.png">

**Comment by lstein** [comment] 2022-10-06 18:04
@pbaylies - first bug report on perlin noise. Could you see if you can reproduce?

**Comment by ioma8** [comment] 2022-10-07 08:46
@pbaylies ah ok. The documentation to treshold doesnt say what are the appropriate values for treshold and writes about values upto 100 so I thought 50 as middle ground would be okish for testing. I will try lower values.

Anyway do different values of Perlin noise change output for you? For me 0.1-0.9 produce exactly same images.

**Comment by ioma8** [comment] 2022-10-07 08:48
@pbaylies ok tested treshold 1.5 and 2 and those produce different result so it seems to be working. Nonetheless it doesnt reduce oversaturation as the documentation suggests, it rather changes texture of the picture, seems to me.

**Comment by pbaylies** [comment] 2022-10-07 08:49
@ioma8 yes, the threshold values are more exponential in nature, by the time you get to 100 you shouldn't see much difference between that and 0 (disabled), but 2 or 5 or 10 is a much saner value in general. Once you get down to 1 you've likely gone too far!

I do see a difference in perlin noise, varying it gives me different generations. I can't test on mps / arm here though, so I don't know why noise would be different?

**Comment by ioma8** [comment] 2022-10-07 08:51
As for the saturation, it seems opposite than what is written in docs. Treshold 1.5 (on same seed and other settings) is more saturated than 0. And 2 is more saturated than 1.5.

Sampler K_euler_a, 20 steps, cfg 5

Treshold 0:
![000103 3120707695](https://user-images.githubusercontent.com/6624752/194513717-1d55a5ae-bfb8-4e34-bec4-85830414967c.png)

Treshold 1.5:
![000104 3120707695](https://user-images.githubusercontent.com/6624752/194513735-557012f4-e3dc-467c-9deb-a7dcb926ccd0.png)

Treshold 2:
![000105 3120707695](https://user-images.githubusercontent.com/6624752/194513762-868f483f-0dff-4586-b454-06eab3c11204.png)

**Comment by pbaylies** [comment] 2022-10-07 08:53
@ioma8 this is a bit subjective, but that looks right to me; I can see that 1.5 is truncating the values more, and 0 is brighter than 2, so, looks like correct behavior.

**Comment by ioma8** [comment] 2022-10-07 08:57
@pbaylies Yes it might limit brightness but its not the same as limiting saturation. Saturation actually goes up. So maybe the docs need updating.

As for the perlin noise. Tried the same prompt, same seed same settings with three different values. The images are EXACTLY the same - I pixel peeped (though as you can see different to perlin 0).

Perlin 0:
![000105 3120707695](https://user-images.githubusercontent.com/6624752/194514803-fdf9d064-014f-4b02-994f-8063b992d66e.png)

Perlin 0.2:
![000106 3120707695](https://user-images.githubusercontent.com/6624752/194514840-45996cb4-db8e-43ae-89ef-310337a0fb33.png)

Perlin 0.4:
![000107 3120707695](https://user-images.githubusercontent.com/6624752/194514859-8a7437fb-f562-446c-9999-36b9a43594a2.png)

Perlin 0.9:
![000108 3120707695](https://user-images.githubusercontent.com/6624752/194514883-29663b5c-b1af-4b15-8df5-e6196753480d.png)

**Comment by pbaylies** [comment] 2022-10-07 09:00
@ioma8 what it actually does is more complex, it really limits the range of the latent values. So "oversaturation" in the sense that they get too high in some scenarios. As for the Perlin behavior, that is quite odd, it should be mixing in the perlin noise proportionally with the regular noise, that's what that value is supposed to do. i.e., at 0.2 you'd get 20% perlin noise, 80% regular noise, which is what I'm seeing.

**Comment by pbaylies** [comment] 2022-10-07 09:05
@ioma8 sure; I think the main thing that I'll have to check is if noise gets handled differently on your platform for some reason.

**Comment by ioma8** [comment] 2022-10-07 09:09
Yes. txt2img.py line 75 seems to be the point. Should i point some logging here into my code?

**Comment by pbaylies** [comment] 2022-10-07 09:12
@ioma8 go ahead; are you on the development branch?

**Comment by ioma8** [comment] 2022-10-07 09:13
@pbaylies yes

**Comment by ioma8** [comment] 2022-10-07 09:14
@pbaylies are you on Discord somewhere so we dont spam the comments?

**Comment by pbaylies** [comment] 2022-10-07 09:15
@ioma8 sure, what's your Discord

**Comment by pbaylies** [comment] 2022-10-07 09:20
@ioma8 ok, sent you a friend request

**Comment by pbaylies** [comment] 2022-10-07 10:09
@lstein we're still investigating this, but I'm wondering if this might  have to do with the computation of the noise itself? Maybe someone else on arm / mps can take a look and see if my perlin noise routine needs to be computing on cpu or something.

**Comment by ioma8** [comment] 2022-10-07 13:38
Is fixed by this PR by me: https://github.com/invoke-ai/InvokeAI/pull/972

**Comment by psychedelicious** [comment] 2022-10-20 14:11
Fixed in #972.

**Closed by psychedelicious** 2022-10-20 14:11 UTC
Labels: bug
