### ISSUE TITLE
macOS: `ModuleNotFoundError: No module named 'ldm'` 

### ISSUE THREAD

**Issue by psychedelicious** [invoke-ai/InvokeAI#723] opened 2022-09-21 01:03 UTC
**Describe your environment**
- GPU: mps
- VRAM: 32 GB unified memory
- CPU arch: arm64
- OS: macOS 12.5.1
- Python: mamba
- Branch: development 810112577fb0ec352a9f51b6e796cbdcef9fcac4

**Describe the bug**
On a fresh environment, running `python scripts/dream.py` fails:
```python
Traceback (most recent call last):
  File "/Users/spencer/Documents/Code/stable-diffusion/scripts/dream.py", line 10, in <module>
    import ldm.dream.readline
ModuleNotFoundError: No module named 'ldm'
```

Reported by i3oc9i on discord, who found that the issue appears at this commit and did much of the troubleshooting:
e33ed45cfc030a8a454fcc49d0b6ebf991a7e079 -Delete redundant backquotes #665

I had an environment from before that commit. With an updated development branch commit 810112577fb0ec352a9f51b6e796cbdcef9fcac4 , I ran `mamba env update -f environment-mac.yaml` and now my environment is broken. 

Making a new env after checking out a commit prior to the problematic one, issue no longer occurs.

- That problematic commit adds `  - protobuf==3.20.1` to `environment-mac.yaml`. Removing that line and making a fresh environment - leaving everything else the same - does not fix the issue
- If you move `dream.py` to the project root, it works. 
- If you delete the line `import ldm.dream.readline`, you get the same error referring to the next line.
- If you open the python REPL, you can `import ldm.dream.readline` just fine

So it seems that the current working directory is somehow not passed to `dream.py`. 

I haven't the slightest clue what could cause this.

**Comment by psychedelicious** [comment] 2022-09-21 01:15
i3oc9i also found that the github workflow is stuck with the same error: https://github.com/invoke-ai/InvokeAI/actions/runs/3094254306/jobs/5007435455

**Comment by psychedelicious** [comment] 2022-09-21 03:59
Ok, so the `scripts` directory is not being added to `sys.path` when running `python scripts/dream.py`. It also affects  running other scripts e.g. `python backend/server.py`. 

Manually adding the `scripts` directory (e.g. `sys.path.append("/Users/spencer/Documents/Code/stable-diffusion/")`) or `""` (`sys.path.append("")`) fixes it.

I have tried to figure out what changed to cause this issue but am at a loss. 

Resident pythonista @tildebyte  ?

**Comment by lstein** [comment] 2022-09-21 04:43
It's not happening on my linux system, but this issue has come up before in a Windows-specific fashion.

Two things to try:

1. `pip install -e .`  (don't forget the dot at the end)
2. In dream.py, move the line `sys.path.append('.')` to the very top of the file so that it is executed before the imports

I have no freakin' idea why that commit got so messed up. The original PR was just a typographical fix to a single file, but instead ended up pulling in changes from a bunch of previous commits in the development branch. I screwed up the merge in some way, it seems.

**Comment by psychedelicious** [comment] 2022-09-21 04:55
`pip install -e .` did fix my environment, thanks! 

Unfortunately the issue is reproducible and happens on a fresh conda install after that problematic commit. What could have changed to cause this issue?

Moving the `sys.path.append('.')` also would work but given that hasn't changed when then problematic commit occurred, I feel like moving it is bypassing an issue somewhere else.

**Comment by lstein** [comment] 2022-09-21 05:38
I think the key clue here is that` pip install -e .` worked once, and then it failed on subsequent tries. *Something* that happens during that first run of the dream script is modifying the local environment. I can't imagine what it could be.

One way to help reduce the problem search space is to first confirm that `pip install -e .` fixes the problem once. Then try launching the backend/server.py script and see if the problem occurs there as well. If it does, we can assume that whatever the problem is, it is occurring in the common modules shared by the dream script and the web backend.

It also might be helpful to insert `print(sys.path)` at various strategic locations in the code. In my environment, before running dream.py or anything like that, it looks like this:

~~~
['', '/u/lstein/projects/SD/stable-diffusion', '/usr/share/pyshared', '/u/lstein/.conda/envs/ldm/lib/python39.zip',
 '/u/lstein/.conda/envs/ldm/lib/python3.9', '/u/lstein/.conda/envs/ldm/lib/python3.9/lib-dynload', 
'/u/lstein/.conda/envs/ldm/lib/python3.9/site-packages', '/u/lstein/projects/SD/stable-diffusion/src/gfpgan', 
'/u/lstein/projects/SD/stable-diffusion/src/clip', '/u/lstein/projects/SD/stable-diffusion/src/taming-transformers', 
'/u/lstein/projects/SD/stable-diffusion/src/k-diffusion']
~~~

I bet at some point in the code, the entry that points at the stable-diffusion directory will disappear.

**Comment by psychedelicious** [comment] 2022-09-21 07:30
Hmm. The scripts worked once then I got the same error. After that `pip install -e .` didn't work. I wiped out all my envs and started fresh from development and `pip install -e .` didn't fix the error. Maybe wiping out my local copy of the repo and starting totally fresh will affect it. 

Anyways, I'll revisit the issue tomorrow. For now I've just moved the `sys.path.append(".")` above all of the ldm imports.

**Comment by holstvoogd** [comment] 2022-09-21 11:42
I've done a bit of checking with git bisect, it seems 7b0cbb34d618098b4072f14870937ee9eb4369a1 causes this issue

**Comment by holstvoogd** [comment] 2022-09-21 13:21
yep, I'm on a mac (m1 mba); I'm having another look at it later today

**Comment by lstein** [comment] 2022-09-21 13:21
This is what comes of reading bug reports late at night. I totally lost track of the fact that this was reported on a Mac system. I got fixated on Windows in some way. Apologies.

Can any Windows users confirm that this bug appears on their systems?

**Comment by holstvoogd** [comment] 2022-09-21 13:24
Wait, ldm.gfpgan.gfpgan_tools was removed, should that just be ldm.restoration.gfpgan.gfpgan orso?

**Comment by lstein** [comment] 2022-09-21 13:31
That's an uncaught bug in server.py, and I'll fix.

**Comment by psychedelicious** [comment] 2022-09-21 13:43
@holstvoogd Yes that's expected, `backend/server.py` is being updated now to use the new restoration module

**Comment by holstvoogd** [comment] 2022-09-21 13:46
Ah, yeah, I see now. nevermind all my comments then. I hadn't noticed this was actually not about backend/server.py 🤦‍♂️

**Comment by lstein** [comment] 2022-09-21 13:52
Oh, I was just testing my fixes to backend/server.py. I will wait for @holstvoogd to commit his PR and work on dream/server.py instead.

**Comment by holstvoogd** [comment] 2022-09-21 14:09
I've found a solution for the issue with script/dream.py:

```
@@ -47,7 +47,7 @@ def main():
     # Loading Face Restoration and ESRGAN Modules
     try:
         gfpgan, codeformer, esrgan = None, None, None
-        from ldm.dream.restoration import Restoration
+        from ldm.dream.restoration.base import Restoration
         restoration = Restoration(opt.gfpgan_dir, opt.gfpgan_model_path, opt.esrgan_bg_tile)
         if opt.restore:
             gfpgan, codeformer = restoration.load_face_restore_models()
```

Restoration was moved from  ldm/restoration/restoration.py to ldm/dream/restoration/base.py, that seems to cause this.

**Comment by holstvoogd** [comment] 2022-09-21 14:21
Looking at other reference to classes from base.py files, this seems to be the correct solution. Not sure why it works on linux though! I'll make a PR for this issue 👍

**Comment by holstvoogd** [comment] 2022-09-21 15:08
Ok, Sorry for the confusion earlier! I was a bit to eager to help & doing other work at the same time.

Now, I've taken time to look closely at what I am actually doing & I can confirm that:
- `python scripts/dream.py` is still broken for new enviroments on the latest development commit
- git bisect suggests this is the breaking commit for me: c0e1fb5f7144995adbea3268f4c2e564aeca229b
- that makes no sense to me, but removing pyproject.toml & running conda env update fixes the issue. also on the latest versions
- running conda update multiple times does not change the behavior
- an empty pyproject.toml also causes issues

I'm not sure, but this feels like a conda bug tbh. Anyway, removing pyproject.toml fixes the issues with `ModuleNotFoundError: No module named 'ldm'`

**Comment by lstein** [comment] 2022-09-21 15:22
- PR #732, which was just committed to development, should fix `python scripts/dream.py`. Please report if it doesn't. There is a  bug tracking issue #619 specifically set up for reporting WebGUI bugs.
- Thanks for tracking down the issue to pyproject.toml. I share your puzzlement. If we can work around the problem just by adding the `sys.path('.')` line to the top of dream.py, I'm going to go with that solution. server.py already does this.

**Comment by tildebyte** [comment] 2022-09-21 16:01
conda is doing something "convenient" (HUGE "airquotes") again, i.e. processing the pyproject.toml *and taking action based on its mere existence*, even thought there are **no directives in there for it**.

FWIW I'm still working on dropping conda, but I'm still seeing unreproducible-on-my-end reports of pip/pew not working properly even on Windows...

FTR, I've built and rebuilt all of my stable and dev venvs locally on Windows 11 with Python3.10 using pip/pew since I can't even remember how long ago... without major incident. Occasionally I hit a dumb typo or something, but it. just. works. here. This isn't to point fingers at users and say "your fault", but rather to express my frustration at not being able to repro install issues locally...

**Comment by lstein** [comment] 2022-09-21 17:42
OK. I'm going to rename `pyproject.toml` to `pyproject.toml.hide`. Hidden behaviors are very frustrating.

**Closed** 2022-09-21 18:13 UTC

**Comment by tildebyte** [comment] 2022-09-21 19:01
@lstein;

>  I wonder if this has something to do with the renaming of the repository?

Almost definitely not. It's some weird behavior of conda trying to use the 'pyproject.toml' (which can be used similarly to 'requirements.txt' or 'environment.yaml') during the install...

**Comment by psychedelicious** [comment] 2022-09-21 21:11
Goodness. That was a saga. Poor little Toml, didn’t know the chaos he sowed. Thanks for the in depth troubleshooting @holstvoogd !

**Comment by taishi55** [comment] 2022-12-11 08:23
I'm having this error message. How can I fix it?

**Comment by crawlchange** [comment] 2023-01-17 04:02
Still the same issue for fresh installs. The basic documentation installation step-by-step is broken. This is serious.
