### ISSUE TITLE
[bug]: sqlite error on Python 3.10

### ISSUE THREAD

**Issue by david92rl** [invoke-ai/InvokeAI#4016] opened 2023-07-26 23:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

16

### What version did you experience this issue on?

3.0.1rc1

### What happened?

Invokeai fails to start with the following error on Debian using python 3.10:

```
# invokeai-web 
[2023-07-26 23:46:59,827]::[InvokeAI]::INFO --> Patchmatch initialized
/root/invokeai/.venv/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
INFO:     Started server process [31339]
INFO:     Waiting for application startup.
[2023-07-26 23:47:00,599]::[InvokeAI]::INFO --> InvokeAI version 3.0.1rc1
[2023-07-26 23:47:00,599]::[InvokeAI]::INFO --> Root directory = /root/invokeai
ERROR:    Traceback (most recent call last):
  File "/root/invokeai/.venv/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/root/invokeai/.venv/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/root/invokeai/.venv/lib/python3.10/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/root/invokeai/.venv/lib/python3.10/site-packages/invokeai/app/api_app.py", line 79, in startup_event
    ApiDependencies.initialize(
  File "/root/invokeai/.venv/lib/python3.10/site-packages/invokeai/app/api/dependencies.py", line 73, in initialize
    graph_execution_manager = SqliteItemStorage[GraphExecutionState](
  File "/usr/local/lib/python3.10/typing.py", line 939, in __call__
    result = self.__origin__(*args, **kwargs)
  File "/root/invokeai/.venv/lib/python3.10/site-packages/invokeai/app/services/sqlite.py", line 34, in __init__
    self._create_table()
  File "/root/invokeai/.venv/lib/python3.10/site-packages/invokeai/app/services/sqlite.py", line 39, in _create_table
    self._cursor.execute(
sqlite3.OperationalError: near "AS": syntax error
```

It looks like the sqlite version that comes with python 3.10 is lower than the one required for generated columns:
```
# python3 -c "import sqlite3; print(sqlite3.sqlite_version)"
3.27.2
```
According to the docs `SQLite introduced the generated columns since version 3.31.0.`

**Comment by Millu** [comment] 2023-07-27 00:19
@david92rl are you able to update to python 3.11 and give it a go? 

@lstein looks like an issue with python 3.10

**Comment by david92rl** [comment] 2023-07-27 16:43
**Update**: I managed to make it work by compiling the latest version of sqlite3 and forcing python to use it with: 
`export LD_LIBRARY_PATH="/usr/local/lib"`

I could prepare a PR for it, but the workaround seems a bit dirty. We could simply update the SQL query to create the table

**Comment by psychedelicious** [comment] 2023-07-31 09:00
Hmm, I'm not convinced that python 3.10 is the issue. It's very strange that you tried python 3.11 and had the same issue.

FWIW, I have python 3.10.6 and sqlite3 `3.37.2`.

I'm not sure why exactly the table uses generated columns, but we'd be happy for a PR to instead create real columns for for this column (which would be the `id` column in `invokeai/app/services/sqlite.py`).

This would require a db migration. We haven't needed to do that yet - we would need to introduce a version table to the db and a function to handle migrations based on that.

Is that something you're interested in working on @david92rl ?

**Comment by teufelweich** [comment] 2023-10-11 16:27
Same for me with sqlite3 `3.26.0` and python `3.11.2`

**Comment by psychedelicious** [comment] 2023-10-12 06:26
@teufelweich
I did some searching and it looks like if your system already has the `sqlite3` libraries installed, python will use the existing version. So updating python or the python `sqlite3` module won't update the system library. 

(Note that the system library & python module are distinct entities.)

So, I think the next step is to update your system's `sqlite3` installation.

For Ubuntu you might run `sudo apt install sqlite3`.

On macOS, `brew install sqlite3` is an option, being sure to follow the post-install instructions to update your `PATH`.

Not sure about windows.

**Comment by psychedelicious** [comment] 2024-04-03 02:11
Closing this as the root cause is understood - out of date system `sqlite3`.

**Closed by psychedelicious** 2024-04-03 02:11 UTC
Labels: bug
