### ISSUE TITLE
[bug]: init model failed

### ISSUE THREAD

**Issue by efwfe** [invoke-ai/InvokeAI#5032] opened 2023-11-03 06:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### What version did you experience this issue on?

the latest version

### What happened?

InvokeAI]::INFO --> Installing https://civitai.com/api/download/models/63006 [10/11]
```
  File "/data/source_codes/InvokeAI/invokeai/backend/install/model_install_backend.py", line 313, in _install_url
    location = download_with_resume(url, Path(staging))
  File "/data/source_codes/InvokeAI/invokeai/backend/util/util.py", line 290, in download_with_resume
    file_name = re.search('filename="(.+)"', resp.headers.get("Content-Disposition")).group(1)
  File "/data/envs/invoke/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

```

**Comment by Husky110** [comment] 2023-11-07 11:26
Can confirm this. Can't install invoke.ai due to this bug.

**Comment by Millu** [comment] 2023-11-08 03:10
@Husky110 @efwfe you can ignore this error and use InvokeAI by launching it through the invoke.bat / invoke.sh script. 

This is caused by a model that used to be included with InvokeAI is no longer available. If you're seeing this screen, it means the installation was successful and you're on the model download step.

**Comment by Millu** [comment] 2023-11-08 03:30
Duplicate of #5009

**Closed by Millu** 2023-11-08 03:30 UTC
Labels: bug, model manager

**Comment by Husky110** [comment] 2023-11-08 08:34
@Millu - That might work if you go via the AutoInstallScript - I've been installing invoke via the manual pip-method (venv) since I have multiple AI-Tools on my computer. 
I was able to figure out that the LoRa "LowRa" is the problem here. Skip that and everything works well. Maybe replace the civitai-link with a huggingface-link or somewhat else. :)

**Comment by Millu** [comment] 2023-11-08 10:40
@Husky110 glad you got it figured out! LowRA has been removed from the default models in the upcoming release
