### ISSUE TITLE
[bug]: Invoke AI stops functioning when adding or installing a new model

### ISSUE THREAD

**Issue by zero2999** [invoke-ai/InvokeAI#6405] opened 2024-05-20 04:31 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

NVIDIA GeForce RTX 3060 Mobile / Max-Q

### GPU VRAM

6GB

### Version number

4.2.1

### Browser

microsoft edge

### What happened

Hello, in versions prior to version 4.x.x, I could download a model and place it in the 'model' folder, and they worked fine. But now, even if I place it in the 'model' folder (which is not immediately detected now and prompts me to place it externally) or download it directly (some fail to download and others do), all the ones I've tried fail. This also happens with Loras and VAE, both for **SD 1.5 and SD XL.** **Now, my system slows down and freezes**, and after that happens, Invoke AI stops and no longer functions, displaying the following:

tokenizer_config.json: 100%|███████████████████| 904/904 [00:00<00:00, 7.18MB/s]
vocab.json: 100%|████████████████████████████| 862k/862k [00:00<00:00, 1.97MB/s]
merges.txt: 100%|████████████████████████████| 525k/525k [00:00<00:00, 1.63MB/s]
special_tokens_map.json: 100%|█████████████████| 389/389 [00:00<00:00, 1.51MB/s]
tokenizer.json: 100%|██████████████████████| 2.22M/2.22M [00:00<00:00, 9.61MB/s]
config.json: 100%|█████████████████████████| 4.88k/4.88k [00:00<00:00, 33.0MB/s]
[2024-05-19 23:05:51,912]::[uvicorn.error]::INFO --> connection closed
./invoke.sh: line 37: 12404 Killed                  invokeai-web $PARAMS

**Therefore, I am no longer able to test new models.**

### What you expected to happen

You anticipated that upon adding or installing a new model, whether directly into the 'model' folder or through a download, it would seamlessly integrate into the Invoke AI system. Specifically, you expected the system to recognize the new model promptly and for it to function without any glitches or performance issues. Furthermore, you expected to be able to test the functionality of the newly added model within the Invoke AI environment without encountering any disruptions.

**Comment by psychedelicious** [comment] 2024-05-20 06:40
To install models from a folder, use the Scan Folder option. **Do not put model files into the application-managed models directory.** See https://invoke-ai.github.io/InvokeAI/installation/050_INSTALLING_MODELS/#other-models

Please provide a link to a model that doesn't install so we can test it.

**Comment by zero2999** [comment] 2024-05-20 16:17
https://civitai.com/models/257749/pony-diffusion-v6-xl

https://civitai.com/api/download/models/290640?type=Model&format=SafeTensor&size=pruned&fp=fp16

**Comment by psychedelicious** [comment] 2024-05-20 23:24
This model installs fine for me. How much RAM does your system have?

**Comment by zero2999** [comment] 2024-05-21 04:49
16 gb Ram

![image](https://github.com/invoke-ai/InvokeAI/assets/3674609/b6cf9f90-704f-4b76-8d05-e28fda98ccf5)

**Comment by psychedelicious** [comment] 2024-05-21 09:31
> the problem is not the installation, but the execution after installation.

Ok, sorry the initial report made it sound like there was a problem installing the model. Please try downloading and generating with this model: https://civitai.com/models/4384/dreamshaper (https://civitai.com/api/download/models/128713)

Does this one work?

**Comment by zero2999** [comment] 2024-05-22 00:41
I installed the model you recommended, and as you can see from the images, it works well. However, I would like to try other models for Stable Diffusion XL, such as Ponny Diffusion, due to its improved image quality. Additionally, I am interested in exploring other models for Stable Diffusion 1.5 to create the graphics I need.

![image](https://github.com/invoke-ai/InvokeAI/assets/3674609/db78037e-d33c-460b-aeeb-77fc5faf56bc)


![image](https://github.com/invoke-ai/InvokeAI/assets/3674609/7e52a91a-599c-4a40-adb6-69e852495fc1)


![image](https://github.com/invoke-ai/InvokeAI/assets/3674609/4ef71301-f7f0-4263-877a-8ea76576e3c0)

**Comment by psychedelicious** [comment] 2024-05-22 01:20
Thanks for trying that. This is a duplicate of #6353, closing it. We have this issue on the roadmap to investigate.

**Closed by psychedelicious** 2024-05-22 01:20 UTC
Labels: bug
