### ISSUE TITLE
Inpainting: Colors underneath the transparent region seem to have been erased

### ISSUE THREAD

**Issue by fungnoth** [invoke-ai/InvokeAI#555] opened 2022-09-13 22:28 UTC
# OK I FOUND THE CAUSE
I don't know if it's a Mac only problem.
But both GIMP and the Web UI replaced the colour behind transparent region to black after cropping.
I spent two and a half hour on documenting this. And got it working.
<img width="284" alt="image" src="https://user-images.githubusercontent.com/7991911/190022272-0eb78ec4-31df-4119-bde0-b515a96f8e49.png">

If I make transparent area before resize/crop, it fails.
If I resize&**CROP**, and then create transparent area, it works.

**Describe your environment**
- GPU: Apple M1
- VRAM: [don't know]
- CPU arch: ARM
- OS: macOS
- Python: Anaconda
- Branch: Main
- Commit: 
```
commit 89da371f4841f7e05da5a1672459d700c3920784 (HEAD -> main, origin/main, origin/HEAD)
Author: David Wager <maddavid123@gmail.com>
Date:   Tue Sep 13 20:17:26 2022 +0100
Fix images in Variations example (#537)
Images had their relative paths broken. Adjust paths.
```

**Describe the bug**
Add image with transparent area to web ui, the output is mostly black in the transparent area.
I tried to follow the GIMP guide on inpainting page, no luck.

**To Reproduce**
OK, I'll try find an image online and do that so that everyone can replicate. I hope it's just my lack of experience with GIMP.

1. Download this image 
https://www.freepik.com/premium-photo/pensive-sad-thoughtful-young-girl-holding-cup-coffee-woman-experiencing-emotional-stress-love-drama-concept_17111746.htm

2. Turn area around her hand & cup to transparent
Unnecessarily detailed steps in GIMP is attached, 
never used GIMP before, always been on photoshop, I hope it's just me messed up here
<details>
<summary><b>View very long Image</b></summary>
<img src="https://user-images.githubusercontent.com/7991911/190018296-97543257-0e7f-421d-9d07-02769cb459f3.jpg">
</details>

3. Upload "export.png" to Web UI, using default settings, seed 2023

4. Output just make the transparency black. It is processed, has something in it, still mostly black.
![Screen shot of many output images](https://user-images.githubusercontent.com/7991911/190019202-a44c30f3-4586-4a51-8ba2-6048aa1cef41.jpg)

**Expected behavior**
Fill something meaningful to the transparent area.

**Additional context**
Is that a bug of some image resizing/cropping code? It really has colour kept, even after I reimport it to gimp and hide the alpha channel.
But if I size and crop in GIMP, export to png, reimport, then it's black under the transparency.
![alpha color preserved](https://user-images.githubusercontent.com/7991911/190020124-94da35a2-46e2-47ea-b058-7beb041c5003.jpg)

Anyway, I'm so grateful that someone is creating a webUI for Macbooks. I'm so amazed by the frequency of you updating this project, and replying to people online at the same time.

**Comment by lstein** [comment] 2022-09-13 23:30
Yes, I'm very frustrated with gimp. It sometimes keeps the color under the transparent area, and sometimes replaces it with the background color. My workflow now is to pass the original image as the init_img, and the same image with transparent areas as the mask. However, this is awkward and error-prone.

I think the inpainting implementation can be fixed by replacing the masked areas with latent noise. This will encourage the inpainter to rapidly progress the masked areas. The problem is that the inpainter deals with solid colored regions very very slowly.

**Comment by fungnoth** [comment] 2022-09-14 08:17
> Yes, I'm very frustrated with gimp. It sometimes keeps the color under the transparent area, and sometimes replaces it with the background color. My workflow now is to pass the original image as the init_img, and the same image with transparent areas as the mask. However, this is awkward and error-prone.
> 
> I think the inpainting implementation can be fixed by replacing the masked areas with latent noise. This will encourage the inpainter to rapidly progress the masked areas. The problem is that the inpainter deals with solid colored regions very very slowly.

Maybe we can filter out anything opacity lower than a particular value. I don't know if semi-transparency means anything here. If it matters, we can make the opacity threshold <= 0.01. If it doesn't, we can make it 0.5, 0.8 or any

**Comment by fungnoth** [comment] 2022-09-16 07:07
Can confirm, I used Photopea and make the transparent area 1% opacity. It works just fine

**Comment by lstein** [comment] 2022-09-17 00:34
Oh cool! This is great to know. In fact, the way the code works is that the mask is applied over any region that is <100% opacity, so no code changes are needed. I'll fix the docs now.

**Comment by fungnoth** [comment] 2022-09-17 06:48
Just tested again, with 1.14.1
Fully transparent mask exported from Photopea doesn't work, but mask density 254 works. I don't know about real photoshop.

https://helpx.adobe.com/photoshop/using/masking-layers.html#root_content_flex_items_position_position-par_multi_column_1063913919

**Comment by svumme** [comment] 2022-09-21 23:40
maybe I'm wrong, it doesn't work well in my opinion. If in the image there is an object with a defined shape (fig1) and it is masked with a black (1,1,1) it works. but if for example you create a mask on a white wall, so where there is no shape, but also for example a homogeneous lawn (fig2), then it doesn't work.
![Capture_011](https://user-images.githubusercontent.com/71202047/191628513-74cdf3e5-c982-42fd-92c7-f24f9a2a6426.JPG)
![Capture1](https://user-images.githubusercontent.com/71202047/191628516-def797b4-4fa9-4e3b-b6c6-aa950843e94d.JPG)

**Comment by fungnoth** [comment] 2022-09-22 06:03
> maybe I'm wrong, it doesn't work well in my opinion. If in the image there is an object with a defined shape (fig1) and it is masked with a black (1,1,1) it works. but if for example you create a mask on a white wall, so where there is no shape, but also for example a homogeneous lawn (fig2), then it doesn't work .in the second image there was no way to create a lake ![Capture_011](https://user-images.githubusercontent.com/71202047/191628513-74cdf3e5-c982-42fd-92c7-f24f9a2a6426.JPG) ![Capture1](https://user-images.githubusercontent.com/71202047/191628516-def797b4-4fa9-4e3b-b6c6-aa950843e94d.JPG)
There's a img2img intensity or something, try set it higher.
Because the diffuser start with existing pixels

**Comment by svumme** [comment] 2022-09-22 10:07
> There's a img2img intensity or something, try set it higher.
> Because the diffuser start with existing pixels
the problem is not solved by changing the values ​​of strech (intensity), here I have better described what, in my opinion, is the problem :https://github.com/invoke-ai/InvokeAI/issues/740

**Comment by tildebyte** [comment] 2022-10-02 21:40
"Recipe for Adobe Photoshop" in [INPAINTING.md](https://github.com/invoke-ai/InvokeAI/blob/development/docs/features/INPAINTING.md#recipe-for-adobe-photoshop) does NOT work, in fact there IS NO "Save colour values from transparent pixels"[1] checkbox when saving/saving as/exporting PNG. Not even the [Super PNG](https://www.fnordware.com/superpng) plugin works.

AFAICT from DDG/Google/et al. (and my own futile efforts), proper masking IS NOT possible with Photoshop.

[1] Apparently a copypasta from GIMP, where there IS a checkbox with *exactly* this name.

**Comment by fungnoth** [comment] 2022-10-02 23:22
> "Recipe for Adobe Photoshop" in [INPAINTING.md](https://github.com/invoke-ai/InvokeAI/blob/development/docs/features/INPAINTING.md#recipe-for-adobe-photoshop) does NOT work, in fact there IS NO "Save colour values from transparent pixels"[1] checkbox when saving/saving as/exporting PNG. Not even the [Super PNG](https://www.fnordware.com/superpng) plugin works.
> 
> AFAICT from DDG/Google/et al. (and my own futile efforts), proper masking IS NOT possible with Photoshop.
> 
> [1] Apparently a copypasta from GIMP, where there IS a checkbox with _exactly_ this name.

Yeah, that's what I mean above, you need to make the cutout area not fully transparent. 0.01 opacity maybe

**Comment by tildebyte** [comment] 2022-10-02 23:25
> you need to make the cutout area not fully transparent

This also doesn't work with PNGs saved from Photoshop.

**Comment by czyz** [comment] 2022-10-07 03:42
I made a cutout transparent area using adobe aftereffects, then made some color solids to paint in the transparent area and set those solids to 1% opacity. And the result is weird.

Here's an input file:
![Horse_battle_2_00000](https://user-images.githubusercontent.com/345036/194462496-4edf5881-410a-4441-99db-7193c613ad73.png)

It was one of an image sequence I processed, using a prompt file that ramped the image strength down from 80% to 30% over 58 images.  dream.py (v2.0.0-rc5 running on Windows 10 Pro in conda) did recognize the image's alpha, and this message showed up in its output: " Initial image has transparent areas. Will inpaint in these regions."

Here's the prompt file:
[Horse_battle_2.txt](https://github.com/invoke-ai/InvokeAI/files/9730512/Horse_battle_2.txt)

Here's the result at 80% image strength, 10 cfg_scale, and 60 steps:
![000006 1111111111](https://user-images.githubusercontent.com/345036/194462588-a596b662-8a35-47d5-9751-b06b5ff84cdd.png)

And then at 58% the colors of my very transparent color solids that painted in the area showed up, but looking very opaque and with no apparent inpainting:
![000032 1111111111](https://user-images.githubusercontent.com/345036/194462892-6352f154-49a0-4003-823e-62421754b0b7.png)

Here's the full sequence, rendered as an mp4, with the source image at lower right (I added a checkerboard and upped the opacity of my color solids to try and indicate the transparent area). The Image Strength values can be read in the text at top-right. Generated image is at left.

https://user-images.githubusercontent.com/345036/194462937-960b5dfa-ce2d-4b41-9c59-11cfd1e1b4fc.mp4

**Comment by czyz** [comment] 2022-10-07 15:28
I should add -- I did the 1% opacity colored shapes to avoid what happens when I leave the area completely transparent, which is that it is rendered as black with just little bits of fringing around the edges where there's probably some color information in the pixels due to anti-aliasing. I didn't know what would happen with the inpainting but was surprised to just see my colored shapes show up as opaque.

**Comment by czyz** [comment] 2022-10-07 17:03
Tried the same images with the plms sampler rather than ddim, with the same result. 
Maybe it'll just start working when the [inpaint-replace](https://github.com/invoke-ai/InvokeAI/pull/891) argument is merged and I send over a png image with no color information in the alpha?

**Closed** 2022-10-24 03:43 UTC
Labels: bug
