### ISSUE TITLE
[bug]: Queue dont start from Canvas is some situations

### ISSUE THREAD

**Issue by vrubzov1957** [invoke-ai/InvokeAI#4814] opened 2023-10-05 23:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

11

### What version did you experience this issue on?

3.2.0rc3

### What happened?

The added queue element cannot be launched from the canvas when Сontrolnet is active, and when the selected area size differs from the entire canvas size. It is in "WarmUp" stage - permamently.

PS: I have Scaling generated image in Canvas enabled manually to 512.

**Comment by Millu** [comment] 2023-10-05 23:46
@psychedelicious does this relate to the cause of #4764 ?

**Comment by vrubzov1957** [comment] 2023-10-06 04:21
> @psychedelicious does this relate to the cause of #4764 ?

It is different situation.

But when we press Cancel in "Warmup" stage as I pointed here (Enabled ControlNet and differ size of box), then we get same as in the cause of #4764 

But also we can get the cause of #4764 when we Cancel a correct "WarmUp" stage, for example few seconds after we added a Queue item.

**Comment by psychedelicious** [comment] 2023-10-09 00:21
@vrubzov1957 I think I've fixed this in #4829, which will be in this week's release.

**Closed** 2023-10-12 10:31 UTC
Labels: bug, unified canvas
