### ISSUE TITLE
[bug]: Touch Event with regional control and control adapters

### ISSUE THREAD

**Issue by thesilentyak** [invoke-ai/InvokeAI#6339] opened 2024-05-10 03:42 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Windows

### GPU vendor

Nvidia (CUDA)

### GPU model

3070 Laptop

### GPU VRAM

8gb

### Version number

4.2

### Browser

Brave browser

### What happened

While a control adapter and or image to image is added  in the control layer portion. Regional control input is blocked and we aren't able to input. This is while using a touch screen ( phone screen or drawing tablet input)

### What you expected to happen

I expected to be able to use the brush and eraser in the regional control layer like usual

### How to reproduce the problem

Use a device with touch input. Add a control or img to img layer. Attempt to use regional control input 

### Additional context

Touch input

### Discord username

Thesilentyak

**Comment by psychedelicious** [comment] 2024-05-10 09:17
I'm pretty sure this is a duplicate of #6331, but we can leave it open in case the fix for that issue doesn't fix this one too. Could be some other touch interaction.

**Closed** 2024-05-12 22:37 UTC
Labels: bug

**Comment by psychedelicious** [comment] 2024-05-12 22:41
If this is still a problem after the next update is released, we will consider it a part of #6319.
