### ISSUE TITLE
[bug]: the files in outputs doesn't load on UI 

### ISSUE THREAD

**Issue by Komachijh** [invoke-ai/InvokeAI#3916] opened 2023-07-23 13:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

4GB

### What version did you experience this issue on?

3.0.0

### What happened?

I reinstalled INVOKE AI 3 in a new folder. 
The installation went okay, but on the side bar, where there are the gallery images, it doesn't show the previously generated images on the thumbnails list. I copied the directory "outputs" from INVOKE AI 2.3.3, as I have done since version 1.5.

Even if I manually import the image and process it with INVOKE AI 2.3.3, it loses the image information, such as prompt and all settings. Since version 1.5, I haven't had any trouble. Can someone help me?

### Contact Details

komachidama@gmail.com

**Comment by Millu** [comment] 2023-07-24 05:26
It's on the radar - captured this here: #3926

**Comment by Komachijh** [comment] 2023-07-24 06:04
Thank you for highlight this!

Il lun 24 lug 2023, 7:26 AM Millun Atluri ***@***.***> ha
scritto:

**Comment by Millu** [comment] 2023-07-25 01:26
Going to close this as a duplicate of #3926

**Closed** 2023-07-25 01:26 UTC
Labels: bug

**Comment by Komachijh** [comment] 2023-07-25 04:49
It is not duplicate because they are different OS. Anyway thank you
i will write another bug today

Il mar 25 lug 2023, 3:26 AM Millun Atluri ***@***.***> ha
scritto:

**Comment by exmachina100** [comment] 2024-02-11 18:41
solution: for me while updating invoke ai, it has created a new backup at c drive - user. 
copy output folder from c drive  to your new desired location
