### ISSUE TITLE
Sequential Seeds with Multiple Outputs

### ISSUE THREAD

**Issue by 19wolf** [invoke-ai/InvokeAI#1174] opened 2022-10-20 01:08 UTC
[From Discord:](https://ptb.discord.com/channels/1020123559063990373/1032399876094439456) "I'd love to see sequential seeds used (e.g. 34, 35, 36, 37, ...) as an option when more than one image is generated via something like --sequential_seeds"

**Comment by lstein** [comment] 2022-10-20 11:25
This can be done. If you exit the web/CLI and relaunch, do you want the seeds to start out again at 1, or pick up where you left off?

**Comment by 19wolf** [comment] 2022-10-20 12:34
I'm not sure if it needs a memory like that, just something like when you set the `-S 1` and `-n 12` (and `--sequential_seeds`), it'll produce images with `-S 1` `-S 2` ... `-S 12`

**Comment by psychedelicious** [comment] 2022-10-20 14:02
This is a duplicate of #909

**Comment by psychedelicious** [comment] 2023-08-06 04:16
This is now the default behavior.

**Closed by psychedelicious** 2023-08-06 04:16 UTC
Labels: enhancement
