### ISSUE TITLE
Is the result consistent  with stable diffusion official when using default parameters?

### ISSUE THREAD

**Issue by xpeng** [invoke-ai/InvokeAI#1075] opened 2022-10-13 01:07 UTC
Since I used [lexica.art](https://lexica.art) or [dream studio official](https://beta.dreamstudio.ai/dream)  for a while to compare result, so we always share seed number and other parameters with friends.

Is the result in InvokeAI consistent  with stable diffusion official when using default parameters? or did i miss something?

Thanks!

**Comment by lstein** [comment] 2022-10-13 02:21
You may or may not get the same images. The code bases started out the same, but have diverged over time. Your best chance for reproducibility is to make sure you are using the same sampler. Older versions of Stable Diffusion source codes defaulted to `plms`, but newer ones tend to use one of the k* samplers, such as `k_euler_a`. We use `k_lms`. 

Macs, due to a difference in their random number generator library, do not produce the same images as Windows or Linux machines.

**Comment by xpeng** [comment] 2022-10-13 03:55
> You may or may not get the same images. The code bases started out the same, but have diverged over time. Your best chance for reproducibility is to make sure you are using the same sampler. Older versions of Stable Diffusion source codes defaulted to `plms`, but newer ones tend to use one of the k* samplers, such as `k_euler_a`. We use `k_lms`.
> 
> Macs, due to a difference in their random number generator library, do not produce the same images as Windows or Linux machines.

Thanks lstein, i'll keep trying. 

I think there may be some random number generator different here, i found there are difference between using "cpu" and "cuda" device in manual_seed(seed) too.

**Comment by psychedelicious** [comment] 2022-10-20 14:48
Closing as the question has been answered

**Closed by psychedelicious** 2022-10-20 14:48 UTC
