### ISSUE TITLE
[bug]: stable diffusion v2.1-768 generates black images

### ISSUE THREAD

**Issue by utiq** [invoke-ai/InvokeAI#2413] opened 2023-01-24 17:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

24GB

### What happened?

I just installed InvokeAI 2.3.0+a0; during the installation process, when it was the moment to select the models to download automatically, I selected recommended (r). Everything is installed OK, and the UI and all the features work fine.
When it's time to generate an image using the model **stable-diffusion-2.1-768**, the system generates black images. I tried changing the sampler and steps, and it's the same. However, if I select the model stable-diffusion-1.5, everything works fine.

### Screenshots

![image](https://user-images.githubusercontent.com/1144196/214370271-6ac4b72c-816d-4d05-9cd0-cfc339ea47ff.png)
![image](https://user-images.githubusercontent.com/1144196/214370402-41936758-368d-4b2c-9421-3a4d76852372.png)

### Additional context

GTX 4090

**Comment by Dizolivemint** [comment] 2023-01-24 21:13
What happens when you set width and height to 768?

**Comment by xaroth8088** [comment] 2023-01-25 00:32
For any dev looking into this, [this issue ](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/5506#issuecomment-1342403028) from the `automatic1111` project may offer some insight.  The short version is that - for whatever reason - the 2.x line seems to require either full precision mode or `xformers` in order to generate non-black images.

**Comment by utiq** [comment] 2023-01-25 01:43
> For any dev looking into this, [this issue ](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/5506#issuecomment-1342403028) from the `automatic1111` project may offer some insight. The short version is that - for whatever reason - the 2.x line seems to require either full precision mode or `xformers` in order to generate non-black images.

how can I set the full precision? if I run this command `python scripts/invoke.py --web --no-half` I get the error `invoke.py: error: unrecognized arguments: --no-half`

**Comment by mickr777** [comment] 2023-01-25 02:58
> > For any dev looking into this, [this issue ](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/5506#issuecomment-1342403028) from the `automatic1111` project may offer some insight. The short version is that - for whatever reason - the 2.x line seems to require either full precision mode or `xformers` in order to generate non-black images.
> 
> how can I set the full precision? if I run this command `python scripts/invoke.py --web --no-half` I get the error `invoke.py: error: unrecognized arguments: --no-half`

try --precision=float32

**Comment by keturn** [comment] 2023-01-25 04:49
duplicate of #2329

**Closed** 2023-01-25 04:50 UTC
Labels: bug
