### ISSUE TITLE
Missing images in Inpainting and Outpainting Doc files

### ISSUE THREAD

**Issue by Any-Winter-4079** [invoke-ai/InvokeAI#1278] opened 2022-10-28 01:19 UTC
https://github.com/invoke-ai/InvokeAI/blob/development/docs/features/INPAINTING.md

The first images are okay

<img width="425" alt="Screenshot 2022-10-28 at 03 16 55" src="https://user-images.githubusercontent.com/50542132/198433966-435744df-63ec-4785-b6ed-cc083137689d.png">

But the last ones are missing

<img width="425" alt="Screenshot 2022-10-28 at 03 17 14" src="https://user-images.githubusercontent.com/50542132/198434103-25d6ab2d-94f7-4dd3-8200-4917d06edaa6.png">

https://github.com/invoke-ai/InvokeAI/blob/development/docs/features/OUTPAINTING.md

In this one, all seem to be missing

<img width="425" alt="Screenshot 2022-10-28 at 03 16 19" src="https://user-images.githubusercontent.com/50542132/198433768-53df71b4-3c3e-4e7a-a348-85af44528250.png">

**Comment by mauwii** [comment] 2022-10-29 14:44
instead of using the github docs, open the docs via it's dedicated GH-Pages at https://invoke-ai.github.io/InvokeAI/features/OUTPAINTING/

for the moment there are only the main docs, but maybe I will find some time to find out how to use [`mike`](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#versioning) with github actions. It's a MkDocs-Addon to enable versioning of the documentation (f.E. having the main and the dev branch selectable). I managed to do so via Azure-Pipelines a while ago which was a pain in the ... But since I am not that used to the GH-Workflow-Syntax, I can't make any promisses when this is going to happen...

**Comment by Any-Winter-4079** [comment] 2022-10-29 18:12
@mauwii wait, but @lstein did an update to https://github.com/invoke-ai/InvokeAI/blob/development/docs/features/OUTPAINTING.md 2 days ago (October 27, 2022), while  https://invoke-ai.github.io/InvokeAI/features/OUTPAINTING/ last update was October 17, 2022 

I guess it's mainly because one is development and the other is main. Is there any development version of the GH-Pages you shared? Otherwise if we have to wait until it's pushed to main to see the images, it's not very good of a solution and the docs will always be behind...

**Comment by Any-Winter-4079** [comment] 2022-10-29 18:17
> for the moment there are only the main docs, but maybe I will find some time to find out how to use [mike](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#versioning) with github actions. It's a MkDocs-Addon to enable versioning of the documentation (f.E. having the main and the dev branch selectable). I managed to do so via Azure-Pipelines a while ago which was a pain in the ... But since I am not that used to the GH-Workflow-Syntax, I can't make any promisses when this is going to happen...

That'd be great. In the meantime, all images should be in the documentation in whatever format the first images are. I mean, some images are visible while other are not. It should just be a matter of using the same format for all.

**Comment by Any-Winter-4079** [comment] 2022-10-29 18:33
Aha!
So this works
`<img src="../assets/still-life-scaled.jpg">`
but this doesn't
`<div align="center" markdown>![step4](../assets/step4.png)</div>`

@mauwii since you're more proficient with GH-Pages, do you think you could find a quick fix for the below image?
Could we simply use `<img src="../assets/step4.png">` or is the div required for some nice formatting? If so, any way to make it work with the div?

**Comment by mauwii** [comment] 2022-10-29 19:12
ignore github and only focus on https://invoke-ai.github.io/InvokeAI/features/INPAINTING/

it has been discussed a lot and in the end you have to decide between good looking [gh-pages](https://invoke-ai.github.io/InvokeAI/), or not rly good looking GH-Pages but also pictures available in reporoot/docs/*.md

it starts with "The Pictures are not working", goes to "why is this formated so strange" to "I fixed all markdown-violations" - where every step just takes out more of the features you get with MkDocs. 

Just wanted to post you some examples, but while doing so just found out that most pages are already broken again 🤦🏻 So maybe it is fine to stay with githubrepo/docs/*.md instead of mkdocs since I honestly don't have the mood to fix those pages every release again and again (spent like 10 hours just formatting those pages, if not more...)

**Comment by mauwii** [comment] 2022-10-29 22:15
> Aha! So this works `<img src="../assets/still-life-scaled.jpg">` but this doesn't `<div align="center" markdown>![step4](../assets/step4.png)</div>`

btw: better Markdown Syntax would be like `![alt-text](image-path/link)`, like this
![screenshot from post 1](https://user-images.githubusercontent.com/50542132/198433966-435744df-63ec-4785-b6ed-cc083137689d.png) (which also works for both "systems" (gh-docs, gh-pages)) and is no markdown violation ;)

**Comment by Any-Winter-4079** [comment] 2022-10-30 04:27
Okay, so then, these 2 options do work in the docs:
```
<img src="../assets/outpainting/curly-outcrop.png">
```
```
![alt-text](../assets/outpainting/curly-outcrop.png)
```
and while the first option looks a bit better in the docs (it's centered)

<img width="1166" alt="Screenshot 2022-10-30 at 05 22 43" src="https://user-images.githubusercontent.com/50542132/198862462-bbeceb8b-c17c-41ca-b5fa-87cde2f72354.png">

you say the second option works also for gh-pages -and I assume the first option doesn't.

@mauwii should we make a conscious effort to use `![alt-text](../assets/outpainting/curly-outcrop.png)` then for images?
I'm tagging @lstein because he was the last person to edit the docs.

**Comment by mauwii** [comment] 2022-10-30 04:55
To center then you would cover this in

```markdown
<figure markdown>
![bla](diffusionpic)
<figcapture> add a nice capture </figcapture>
</figure>
```

which would then break the GH docs again

Believe me, there is only two ugly docs or one beautiful doc (without having the necesarrity of maintaining two seperate docs with f.E. a extra Branch or a wiki or whatever)

**Comment by Any-Winter-4079** [comment] 2022-10-30 06:11
Yeah, personally I'd rather work on something else too -such as testing out new features😄.

I opened the issue because there is no doc version with latest changes + images. Either we have gh-pages and nicely looking images but not the latest features, or gh-docs with latest features documented but no images to support them.🙈

I think a decision should be made moving forward (e.g. use only gh-pages, or only gh-docs, or a compromise -maybe `![alt-text](path)` so that images work for both?), and we should all stick to it.

Otherwise it's going to be a mess and tiring, as you express, constantly discussing this, fixing errors, etc.

From my side, I don't have a strong opinion on this. I'd only suggest to have one place where we have latest documentation changes + images. From there, we can think of making it nicely-looking.

We can let @lstein read through and decide :P

**Comment by mauwii** [comment] 2022-10-30 06:17
If you are fit with GitHub Actions, implement [Mike](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#versioning) which would result in having more versions of the GH-Pages on the same site (as seen [here](https://mauwii.github.io/azure-pipelines-with-github-repo/main.679/), the "main" switch in the top)

**Comment by Any-Winter-4079** [comment] 2022-10-30 06:25
> Or Option 3 --> read the docs locally via mkdocs serve 🤓

Oh, this is awesome!

**Comment by mauwii** [comment] 2022-10-30 06:51
IF  Developers are not able to use `mkdocs serve` to look at the docs for the **Development** branch localy, then I would advise them to get a new hobby 🤭

I mean it is not a "Latest" branch, but a constantly changing- nobody knows if a feature will be released/changed/removed- kind of branch, which for the end user is nothing from benefit, but just my 2 cents ...

**Comment by Any-Winter-4079** [comment] 2022-10-30 11:09
Well, it's very easy to serve: install dependencies and then `mkdocs serve`. I meant it more in ways such as not being home to serve locally (e.g. reading gh-docs from Github) or not knowing this option exists. I mean, when I go to the docs on Github -e.g. https://github.com/invoke-ai/InvokeAI/blob/development/docs/features/POSTPROCESS.md - nothing tells me: hey, you should view this locally running `mkdocs serve`. Hence, I would have never guessed it.

**Comment by Any-Winter-4079** [comment] 2022-10-30 11:17
> And since imho the most people even don't read the docs at all, I rly don't understand why everybody is behaving like "oh my god - the docs - THE DOCS" ;P

Personally, I read them when there is a new feature I haven't caught in the Pull Requests, Issues, etc. and I want to know a bit more about how it works than what I get running `-h`. Other than that,I never read the docs.

Anyway, that's it for me discussing docs 😅  I'll let lstein see the actual state and consider paths forward. For today, I'm switching to trying to figure out what on earth is wrong with outcropping when I use it 😮

**Comment by mauwii** [comment] 2022-10-30 12:01
> Well, it's very easy to serve: install dependencies and then `mkdocs serve`. I meant it more in ways such as not being home to serve locally (e.g. reading gh-docs from Github) or not knowing this option exists. I mean, when I go to the docs on Github -e.g. https://github.com/invoke-ai/InvokeAI/blob/development/docs/features/POSTPROCESS.md - nothing tells me: hey, you should view this locally running `mkdocs serve`. Hence, I would have never guessed it.

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/40327258/198876981-aaa2804c-7ba0-4a88-ac76-04a580d8d092.png">

This are the first 10 lines in the main file `index.md` 🤣 Also don't understand how broken github docs could be better than broken MkDocs for people not on the computer for the moment (So at least I am sure that switching to GH-Docs would not stop the docs from breaking, which is caused by the way of Force-Pushing and Rebaseing is used here which makes it often necesarry to solve merge conflicts, which then leads to people choosing the wrong changes to keep and creating some whitespace changes, .... Also don't mix "latest changes" and "Development Branch", which are two complete different things...

**Comment by Any-Winter-4079** [comment] 2022-10-30 13:57
Personally, I don't want to drag this topic around, but I disagree in terms of UX.

When you visit https://github.com/invoke-ai/InvokeAI/blob/development/docs/index.md you don't see any mention of `mkdocs`. You only see it when you **edit** the file. Or open the file in VSCode, etc.
To me this is the equivalent of having the instructions for a website as HTML comments and then telling users: well, duh, don't you see it's explained there? Just open Inspect Elements!

And it terms of latest changes, sure, there's feature-specific branches that may be more advanced, but in general the development branch is pretty close to having the latest changes (in a general sense, not feature-specific), even more so when we're comparing it with main branch. I'll give you an example. 
This doc https://github.com/invoke-ai/InvokeAI/blob/development/docs/features/INPAINTING.md documents a feature (Using the RunwayML inpainting model, for 1.5 inpainting) that is not available on main branch. Imagine I added some image in that section. Then, if I visit the gh-pages, that section won't be there because gh-pages follows main branch. And if I visit gh-docs here, I will see the text but not the image, because the image is inserted to look nicely on gh-pages.

I mean, you've given very good suggestions ❤️  (e.g. gh-page for dev, among many others) to fix these problems and I leave it to @lstein to choose actions to take (if any), but no, I don't find it intuitive the way things are now (doesn't matter if there are ways to do it, such as clicking edit, and whatnot).

**Comment by mauwii** [comment] 2022-10-30 14:03
I just try to understand what needs to be changed to make it more obvious, I guess here comes the already long necesarry `CONTRIUTING.md` in place, where it then should also be mentioned that docs are served via MkDocs, so if anybody who wants to contribute is aware of this.

I also already thought about adding a README.txt to the docs folder to clarify it's MkDocs, but on the other Hand I am pretty sure that still most people would ignore this file when contributing 🤔

**Comment by Any-Winter-4079** [comment] 2022-10-30 14:18
> I just try to understand what needs to be changed to make it more obvious

The most obvious to me would be a short text at the top of every doc. 
<img width="1050" alt="Screenshot 2022-10-30 at 15 14 09" src="https://user-images.githubusercontent.com/50542132/198883320-132444c7-9739-4830-abdc-efd021fc8867.png">
Like this but well done, of course (not as bad as I did it) 😄 

That would be the best because it covers the most points of entry (e.g. a user may go directly to POSPROCESSING doc without bothering to read the README.md in https://github.com/invoke-ai/InvokeAI/tree/development

**Comment by Any-Winter-4079** [comment] 2022-10-30 14:22
> I also already thought about adding a README.txt to the docs folder to clarify it's MkDocs, but on the other Hand I am pretty sure that still most people would ignore this file when contributing 🤔

Yeah, I agree.

**Comment by mauwii** [comment] 2022-10-30 14:26
> > I just try to understand what needs to be changed to make it more obvious
> 
> The most obvious to me would be a short text at the top of every doc. <img alt="Screenshot 2022-10-30 at 15 14 09" width="1050" src="https://user-images.githubusercontent.com/50542132/198883320-132444c7-9739-4830-abdc-efd021fc8867.png"> Like this but well done, of course (not as bad as I did it) 😄
> 
> That would be the best because it covers the most points of entry (e.g. a user may go directly to POSPROCESSING doc without bothering to read the README.md in https://github.com/invoke-ai/InvokeAI/tree/development

Redundant Information just creates a maintanance overhead and instead of pointing out how to serve localy, the end user would have more benifit from pointing to the correct place to read the docs ;P (didn't u also mention that if you want to read the docs while not on a computer, so this would not help a lot :P )

**Comment by Any-Winter-4079** [comment] 2022-10-30 14:28
Yeah, you are right in it being redundant. And yes, this solution alone would not help in cases such as not being on your local computer.

**Comment by Any-Winter-4079** [comment] 2022-10-30 14:38
Ideally, I would have it here, as a tab. Called Documentation. With the hope of being so obvious, that it becomes the central point of accessing the docs. Then we could have the message there, explaining we use mkdocs, etc.
<img width="1059" alt="Screenshot 2022-10-30 at 15 35 10" src="https://user-images.githubusercontent.com/50542132/198884368-a6da5f80-76ac-4b6a-87be-553a2baaba7f.png">

And it'd be a single point where the info is (not redundant, and removes maintenance overhead as you rightfully say)

**Comment by mauwii** [comment] 2022-10-30 14:57
> The most obvious to me would be a short text at the top of every doc.

This is not redundance? ok xD

And maybe we should stay realistic with a solution and not try to update GitHub with new features...

The default place to link to your docs is the informatin category on the right in repo:
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/40327258/198885478-76e1fad4-ebe1-4932-8e6e-e0207f596349.png">

And I would asume people who do not look at this would also not look at the menubar ...

But this is getting pointless somehow, so I'm out, have a good one.

**Comment by Any-Winter-4079** [comment] 2022-10-30 15:37
> Yeah, you are right in it being redundant

Yep, it's redundant. It's what I said haha.

**Comment by psychedelicious** [comment] 2022-11-23 00:14
I think we came to *some* sort of an agreement here...

**Closed by psychedelicious** 2022-11-23 00:14 UTC
