### ISSUE TITLE
[bug]: can't use !import_model

### ISSUE THREAD

**Issue by Roblouisck** [invoke-ai/InvokeAI#1444] opened 2022-11-11 09:43 UTC
Getting event not found for import_model. I'm on m1 mac.

Was simply trying to follow the docs - https://invoke-ai.github.io/InvokeAI/installation/INSTALLING_MODELS/

```
robert@Roberts-MacBook-Pro InvokeAI % conda activate invokeai
(invokeai) robert@Roberts-MacBook-Pro InvokeAI % !import_model /Users/robert/Documents/InvokeAI/models/ldm/stable-diffusion-v1/model.ckpt
zsh: event not found: import_model
(invokeai) robert@Roberts-MacBook-Pro InvokeAI % 
```

**Comment by mikedg1** [comment] 2022-11-11 14:33
@Roblouisck Looks like you did not execute this in the invokeai command line client and just executed it in your normal terminal.
Looks like you may have missed step 2 of the _Installation via the CLI_
Launch the invoke.py CLI with python scripts/invoke.py.

You terminal should show something like ` invoke>`
Enter your command there.

**Comment by psychedelicious** [comment] 2022-11-23 00:42
Closing as the problem is clear and solution in comments - please let us know if there are other issues by creating a new GH issue.

**Closed by psychedelicious** 2022-11-23 00:42 UTC
Labels: bug
