### ISSUE TITLE
[bug]: 'Use Prompt' and 'Use All' buttons stop to work

### ISSUE THREAD

**Issue by i3oc9i** [invoke-ai/InvokeAI#2587] opened 2023-02-08 15:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

macOS

### GPU

mps

### VRAM

128G

### What happened?

I update to the last commit of the main branch 72357266a633e56f705395396af81aa680aa53d0

I remark that the 'Use Prompt' and 'Use All' buttons are not working any more.

 the other buttons are ok...

**Comment by i3oc9i** [comment] 2023-02-08 15:42
Seem limited to Safari anyway, I tried with all the other browser and they work.

Safari is my main browser, and I always use this browser with Invoke.

I tried to reset the UI, and also to clear the cache related to Invokeai, but these actions do not solve the issue.
All the other button works as far I tested them, only these two do not...

**Comment by lstein** [comment] 2023-02-08 15:50
This is an apparent duplicate of #2578 .The bug appears to affect web browsers that use Apple's web framework.

**Comment by lstein** [comment] 2023-02-08 15:54
This is fixed by #2582 . Thanks for the report!

**Closed by lstein** 2023-02-08 15:54 UTC
Labels: bug
