### ISSUE TITLE
[enhancement]: Canvas - Box Region Selection - Make the ratio of Manual Scaled to Original Box Region Selection equal

### ISSUE THREAD

**Issue by sonny4723** [invoke-ai/InvokeAI#6416] opened 2024-05-21 10:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

Sometimes on Canvas, I have to downscale of the box regional selection to get better result (especially SD1.5) if its dimensions are too large ( larger than 1024 for example). So, the current manual scaled ratio feature is not equal to the original box regional selection by automatically. And I have to do math to input the correct ratio manual downscale dimensions for now.

I hope the manual scaled dimensions should be changed automatically to fit the original ratio whenever I change one of the Width or Height of it.

Sorry for my English if I have any misunderstanding words.

**Comment by ufuksarp** [comment] 2024-05-21 13:38
Duplicate of #5590

**Comment by psychedelicious** [comment] 2024-05-21 23:53
Thanks, closed as duplicate of #5590, please give that issue a thumbs up

**Closed by psychedelicious** 2024-05-21 23:53 UTC
Labels: enhancement
