### ISSUE TITLE
[bug]: Automated installer fails on python 3.12

### ISSUE THREAD

**Issue by Descent098** [invoke-ai/InvokeAI#5153] opened 2023-11-22 20:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

12

### What version did you experience this issue on?

3.4.0post2

### What happened?

When running the automated installer there is an error that states `distutils` package is not installed for one of the dependencies. This issue only occurs on python 3.12+ since the package was removed. 

Since this system is popular for people who might have just installed the latest version it might be worth noting somewhere in the documentation, or worth adding a note to the auto-installer that 3.12 is not yet supported if it's detected as the running version.

Steps to repeat issue:

1. install python 3.12 on machine and register it as main install (add to path)
2. Run the invoke ai auto installer
3. **Error when installing dependencies**

**Comment by kakachiex2** [comment] 2023-11-22 20:48
This happens to me; the problem is because you have python 3.12 and InvokeAi is compatible with pithon 3.11+
by adding python 3.11.6 as default will solve this problem in the environment variable.

**Comment by Descent098** [comment] 2023-11-22 21:33
> This happens to me; the problem is because you have python 3.12 and InvokeAi is compatible with pithon 3.11+ by adding python 3.11.6 as default will solve this problem in the environment variable.

Yeah, downgrading to 3.10<= and <3.12 works, but there should probably just be a notice either on the site or in the installer just because a lot of users will likely not know this is the issue! In the automated installer something like a catch with a suggestion for troubleshooting steps (including supported versions) would be handy!

**Comment by kakachiex2** [comment] 2023-11-22 22:23
Yes the installer need to detect the python version and give the warning but I' think this info is in the readme file

**Comment by Millu** [comment] 2023-11-22 22:30
> Yeah, downgrading to 3.10<= and <3.12 works, but there should probably just be a notice either on the site or in the installer just because a lot of users will likely not know this is the issue! In the automated installer something like a catch with a suggestion for troubleshooting steps (including supported versions) would be handy!

This is great suggestion - can you file an enhancement for this? 

Going to close this issue out for now.

**Closed by Millu** 2023-11-22 22:30 UTC
Labels: bug
