### ISSUE TITLE
[bug]: concept lib name isn't correctly replaced with repo name when saving PNG metadata

### ISSUE THREAD

**Issue by JPPhoto** [invoke-ai/InvokeAI#1599] opened 2022-11-28 18:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

12GB

### What happened?

This report illustrates three separate issues for @damian0815 and @lstein to look at.

1. When requesting a concept with spaces (prohibited), InvokeAI crashes. See this snippet:
```
│ /home/jovyan/work/InvokeAI/ldm/invoke/concepts_lib.py:101 in get_concept_file                    │
│                                                                                                  │
│    98 │                                                                                          │
│    99 │   def get_concept_file(self, concept_name:str, file_name:str='learned_embeds.bin' , lo   │
│   100 │   │   if not self.concept_is_downloaded(concept_name) and not local_only:                │
│ ❱ 101 │   │   │   self.download_concept(concept_name)                                            │
│   102 │   │   path = os.path.join(self._concept_path(concept_name), file_name)                   │
│   103 │   │   return path if os.path.exists(path) else None                                      │
│   104                                                                                            │
│                                                                                                  │
│ /home/jovyan/work/InvokeAI/ldm/invoke/concepts_lib.py:131 in download_concept                    │
│                                                                                                  │
│   128 │   │   print(f'>> Downloading {repo_id}...',end='')                                       │
│   129 │   │   try:                                                                               │
│   130 │   │   │   for file in ('README.md','learned_embeds.bin','token_identifier.txt','type_o   │
│ ❱ 131 │   │   │   │   url = hf_hub_url(repo_id, file)                                            │
│   132 │   │   │   │   request.urlretrieve(url, os.path.join(dest,file),reporthook=tally_downlo   │
│   133 │   │   except ul_error.HTTPError as e:                                                    │
│   134 │   │   │   if e.code==404:                                                                │
│                                                                                                  │
│ /home/jovyan/.conda/envs/invokeai/lib/python3.9/site-packages/huggingface_hub/utils/_validators. │
│ py:114 in _inner_fn                                                                              │
│                                                                                                  │
│   111 │   │   │   kwargs.items(),  # Kwargs values                                               │
│   112 │   │   ):                                                                                 │
│   113 │   │   │   if arg_name == "repo_id":                                                      │
│ ❱ 114 │   │   │   │   validate_repo_id(arg_value)                                                │
│   115 │   │   │                                                                                  │
│   116 │   │   │   elif arg_name == "token" and arg_value is not None:                            │
│   117 │   │   │   │   has_token = True                                                           │
│                                                                                                  │
│ /home/jovyan/.conda/envs/invokeai/lib/python3.9/site-packages/huggingface_hub/utils/_validators. │
│ py:172 in validate_repo_id                                                                       │
│                                                                                                  │
│   169 │   │   )                                                                                  │
│   170 │                                                                                          │
│   171 │   if not REPO_ID_REGEX.match(repo_id):                                                   │
│ ❱ 172 │   │   raise HFValidationError(                                                           │
│   173 │   │   │   "Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are"      │
│   174 │   │   │   " forbidden, '-' and '.' cannot start or end the name, max length is 96:"      │
│   175 │   │   │   f" '{repo_id}'."                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```
2. The erroneous concept name is exposed and may be passed through directly as an HTTP request (per a conversation with @damian0815).
3. The metadata from a successful use of the concept has the "pretty name" rather than the name-separated-by-hyphens, meaning that using `!fetch` at a later point will not work properly. (That's how I encountered these issues.)

**Comment by damian0815** [comment] 2022-11-28 18:50
i was able to reproduce the `!fetch` issue by doing:
```
invoke> a dog <3d-female-cyborgs> -s 2
...
[317] /Users/damian/2.current/stablediffusion/stable-diffusion/outputs/img-samples/000834.3191450485.png: a dog <A female cyborg> -s 2 -S 3191450485 -W 512 -H 512 -C 7.5 -A k_lms

invoke> !fetch /Users/damian/2.current/stablediffusion/stable-diffusion/outputs/img-samples/000834.3191450485.png
invoke> a dog <A female cyborg> -s 2 -S 3191450485 -W 512 -H 512 -C 7.5 -A k_lms
```

**Comment by damian0815** [comment] 2022-11-28 19:20
i have found the cause of the rogue web access attempt and am about to submit a fix.

**Comment by lstein** [comment] 2022-11-29 18:20
I believe this is now fixed in `development`. I will close this issue for now. Feel free to reopen if it is not in fact completely fixed.

**Closed by lstein** 2022-11-29 18:20 UTC
Labels: bug
