### ISSUE TITLE
[enhancement]: More LORA For flux support.

### ISSUE THREAD

**Issue by m4iccc** [invoke-ai/InvokeAI#7092] opened 2024-10-10 16:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What should this feature add?

I'm trying to add a Lora safetensor which I trained on citvitai using the Fast Flux Lora training, however invoke seems to have some issue loading it, please expand on the lora compatibility for Flux, ty!

The error log is in the comments bellow:

**Comment by mrudat** [comment] 2024-10-12 08:50
Do you get the error "Failed: Unknown LoRA type: <filename>"? Is it triggered by, for example, [SameFace fix [Flux Lora]](https://civitai.com/models/766608/sameface-fix-flux-lora)? It's only 4.5MB, so it might be a reasonable test case.

**Comment by m4iccc** [comment] 2024-10-12 10:56
It says the following in red colored letters:

[2024-10-12 04:55:59,643]::[InvokeAI]::ERROR --> Error while invoking session 750905db-8559-414f-b895-61ef83368d7c, invocation 6d1308c0-ebde-449b-8222-675ad635707d (flux_text_encoder): Files for model 'Abstract Oil Spill generator_epoch_1' not found at E:\StableDiffusion\loras\Abstract Oil Spill generator_epoch_1.safetensors
[2024-10-12 04:55:59,643]::[InvokeAI]::ERROR --> Traceback (most recent call last):
  File "C:\Users\Cinem\Downloads\InvokeAI\.venv\lib\site-packages\invokeai\app\services\session_processor\session_processor_default.py", line 129, in run_node
    output = invocation.invoke_internal(context=context, services=self._services)
  File "C:\Users\Cinem\Downloads\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\baseinvocation.py", line 290, in invoke_internal
    output = self.invoke(context)
  File "C:\Users\Cinem\Downloads\InvokeAI\.venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Cinem\Downloads\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\flux_text_encoder.py", line 51, in invoke
    clip_embeddings = self._clip_encode(context)
  File "C:\Users\Cinem\Downloads\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\flux_text_encoder.py", line 100, in _clip_encode
    exit_stack.enter_context(
  File "C:\Users\Cinem\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 492, in enter_context
    result = _cm_type.__enter__(cm)
  File "C:\Users\Cinem\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Users\Cinem\Downloads\InvokeAI\.venv\lib\site-packages\invokeai\backend\lora\lora_patcher.py", line 42, in apply_lora_patches
    for patch, patch_weight in patches:
  File "C:\Users\Cinem\Downloads\InvokeAI\.venv\lib\site-packages\invokeai\app\invocations\flux_text_encoder.py", line 121, in _clip_lora_iterator
    lora_info = context.models.load(lora.lora)
  File "C:\Users\Cinem\Downloads\InvokeAI\.venv\lib\site-packages\invokeai\app\services\shared\invocation_context.py", line 370, in load
    return self._services.model_manager.load.load_model(model, _submodel_type)
  File "C:\Users\Cinem\Downloads\InvokeAI\.venv\lib\site-packages\invokeai\app\services\model_load\model_load_default.py", line 70, in load_model
    ).load_model(model_config, submodel_type)
  File "C:\Users\Cinem\Downloads\InvokeAI\.venv\lib\site-packages\invokeai\backend\model_manager\load\load_default.py", line 53, in load_model
    raise InvalidModelConfigException(f"Files for model '{model_config.name}' not found at {model_path}")
invokeai.backend.model_manager.config.InvalidModelConfigException: Files for model 'Abstract Oil Spill generator_epoch_1' not found at E:\StableDiffusion\loras\Abstract Oil Spill generator_epoch_1.safetensors

**Comment by psychedelicious** [comment] 2024-10-16 21:52
Can you please link to an affected LoRA so we have something to test with?

**Comment by m4iccc** [comment] 2024-10-18 00:35
https://civitai.com/models/789690/abstract-oil-spill-generator

Thank you guys!

**Comment by RyanJDick** [comment] 2024-11-14 17:28
This is a duplicate of #7129 . It was fixed in #7313 , and will be included in the next release.

**Closed by RyanJDick** 2024-11-14 17:28 UTC
Labels: enhancement

**Comment by Dinairune** [comment] 2025-01-04 11:26
bug?  after training flux-lora for my image and after creating many pictures successfully, something happened and now every new picture request i make doesn't use the trainings and the pictures no longer look like me. what can i do?

**Comment by RyanJDick** [comment] 2025-01-08 16:16
> bug? after training flux-lora for my image and after creating many pictures successfully, something happened and now every new picture request i make doesn't use the trainings and the pictures no longer look like me. what can i do?

@Dinairune Please fill out a new bug report. The details requested in the bug report template will help us better understand your issue.
