### ISSUE TITLE
[bug]: v3 ESRGAN models not detected during install and model scan from third party directory.

### ISSUE THREAD

**Issue by cchance27** [invoke-ai/InvokeAI#3880] opened 2023-07-21 23:06 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### VRAM

8GB

### What version did you experience this issue on?

3.0.0

### What happened?

When performing a model scan from the CLI or running the reinitialize i notice that when it scans my a1111 model folder, it seems to detect the standard models fine, and even my loras... however when it hits the ESRGAN models it appears the system doesn't support them and ignores them...

### Screenshots

[2023-07-21 19:04:32,709]::[InvokeAI]::WARNING --> Unable to determine model type for d:\stable-diffusion-webui\models\body_pose_model.pth
[2023-07-21 19:04:36,772]::[InvokeAI]::WARNING --> Unable to determine model type for d:\stable-diffusion-webui\models\BLIP\model_base_caption_capfilt_large.pth
[2023-07-21 19:04:39,029]::[InvokeAI]::WARNING --> Unable to determine model type for d:\stable-diffusion-webui\models\Codeformer\codeformer-v0.1.0.pth
[2023-07-21 19:04:39,218]::[InvokeAI]::WARNING --> Unable to determine model type for d:\stable-diffusion-webui\models\ESRGAN\1x-ITF-SkinDiffDetail-Lite-v1.pth
[2023-07-21 19:04:39,944]::[InvokeAI]::WARNING --> Unable to determine model type for d:\stable-diffusion-webui\models\ESRGAN\4x-UltraSharp.pth
[2023-07-21 19:04:41,090]::[InvokeAI]::WARNING --> Unable to determine model type for d:\stable-diffusion-webui\models\ESRGAN\4x_foolhardy_Remacri.pth
[2023-07-21 19:04:41,530]::[InvokeAI]::WARNING --> Unable to determine model type for d:\stable-diffusion-webui\models\ESRGAN\4x_NMKD-Superscale-SP_178000_G.pth
[2023-07-21 19:04:42,773]::[InvokeAI]::WARNING --> Unable to determine model type for d:\stable-diffusion-webui\models\ESRGAN\4x_RealisticRescaler_100000_G.pth
[2023-07-21 19:04:42,835]::[InvokeAI]::WARNING --> Unable to determine model type for d:\stable-diffusion-webui\models\ESRGAN\realesr-general-wdn-x4v3.pth
[2023-07-21 19:04:42,882]::[InvokeAI]::WARNING --> Unable to determine model type for d:\stable-diffusion-webui\models\ESRGAN\realesr-general-x4v3.pth
[2023-07-21 19:04:43,496]::[InvokeAI]::WARNING --> Unable to determine model type for d:\stable-diffusion-webui\models\ESRGAN\RealESRGAN_x4plus.pth
[2023-07-21 19:04:43,921]::[InvokeAI]::WARNING --> Unable to determine model type for d:\stable-diffusion-webui\models\ESRGAN\TGHQFace8x_500k.pth

**Comment by psychedelicious** [comment] 2023-07-22 01:29
This is not a bug, the functionality is not yet implemented. We opted to get the base upscaling feature working ASAP, and add custom model support in the future. See #3743 for the enhancement. I'm closing this as `duplicate`.

**Closed by psychedelicious** 2023-07-22 01:29 UTC
Labels: bug
