### ISSUE TITLE
[bug]: Could not read metadata

### ISSUE THREAD

**Issue by apfelnymous** [invoke-ai/InvokeAI#1461] opened 2022-11-12 22:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Linux

### GPU

cuda

### VRAM

6GB

### What happened?

Can't read metadata ?!

```
invoke> !fix /home/apfelkomplott/Pictures/beautifulvampirewoman.png --outcrop top 128
>> fixing /home/apfelkomplott/Pictures/beautifulvampirewoman.png
>> could not read metadata
Traceback (most recent call last):
  File "/home/apfelkomplott/InvokeAI/ldm/invoke/args.py", line 1036, in metadata_loads
    images = [metadata['sd-metadata']['image']]
KeyError: 'image'
```

### Screenshots

![IndexError](https://user-images.githubusercontent.com/7989160/201496660-eeec09e9-e690-431a-8077-4425bc37e8a6.png)

**Comment by lstein** [comment] 2022-11-13 02:24
This is fixed in release 2.1.3, which should be released imminently.

**Comment by downj05** [comment] 2022-11-14 20:34
Had a similar issue, when no metadata is provided and I am using my own prompt (in my case with outcropping) it still excepts metadata and throws an uncaught error that crashes the entire script.

**Comment by psychedelicious** [comment] 2022-11-15 02:53
@lstein Looks like there are still some issues with this

**Comment by lstein** [comment] 2022-11-16 04:08
I'm afraid I can't reproduce the issue when I choose a random picture from the Internet that has **no** metadata in it. Here's a JPG of Beyonce accepting a Grammy nomination earlier this week:
![Beyonce-Grammys](https://user-images.githubusercontent.com/111189/202080740-0f2f6a79-4a4b-4aae-8d66-4ac7d8142e7b.jpg)

And here's the outcropped image after extending 128 pixels at the bottom using `--outcrop 128`:
![Beyonce-Grammys 0 outcrop-01](https://user-images.githubusercontent.com/111189/202080894-6805c3f2-58c9-4198-82c1-d58ed86c235a.png)

This was using 2.1.3 and the `inpainting-1.5` model. I didn't even add a prompt or seed and let it use its default seed of 0 and prompt of "".  Can @apfelnymous and @downj05 confirm that you are both experiencing the problem in the new release? Maybe you could post images that are causing the bug to appear?

**Comment by lstein** [comment] 2022-11-21 07:19
I've made a pull request that will fix this bug, and it should appear in the next point release sometime this week.

Here is your outcropped vampire. I reduced her in size a bit for the purpose of debugging. For best results on a non-InvokeAI-generated image, please use the `inpainting-1.5` model.

![vampire-smaller 1817183064 outcrop](https://user-images.githubusercontent.com/111189/202988470-3d0691d9-8300-4663-bca0-a778a81bf200.png)

**Closed as completed** 2022-12-02 10:23 UTC
Labels: bug
