### ISSUE TITLE
Img2Img Not working on K-Samplers at low Img2Img strength

### ISSUE THREAD

**Issue by hipsterusername** [invoke-ai/InvokeAI#898] opened 2022-10-03 18:34 UTC
**Describe your environment**
- GPU: cuda
- VRAM: 12
- CPU arch: x95
- OS: Windows
- Python: anaconda
- Branch: New WebUI PR

**Describe the bug**
Img2Img outputs are greatly deteriorated at low img2img strengths on any of the K samplers (tested using the new WebUI)

**To Reproduce**
1. Upload an init image
2. Using .25 strength, generate a new image using DDIM - Works!
3. Using .25 strength, generate a new image using any of the K-samplers - Yikes!

**Expected behavior**
Output generated that behaves similar to working samplers like DDIM.

**Screenshots**
Original Output:
![image](https://user-images.githubusercontent.com/31807370/193652490-210d5e38-98ac-44f2-abaf-e9065388529d.png)

DDIM @ .25:
![image](https://user-images.githubusercontent.com/31807370/193652526-fa48ee6e-49ee-4cf5-9c50-7ea5355cd0b4.png)

K samplers @ .25:
![image](https://user-images.githubusercontent.com/31807370/193652547-f9d290de-ee7d-4fb9-861d-b07663af94b4.png)

**Additional context**
@lstein - Believe this is related to recent img2img work you've been tackling.

**Comment by psychedelicious** [comment] 2022-10-03 20:33
Duplicate of #889

**Closed by psychedelicious** 2022-10-03 20:33 UTC
Labels: duplicate
