### ISSUE TITLE
[bug]: The image is shifted in canvas mode

### ISSUE THREAD

**Issue by Vasyanator** [invoke-ai/InvokeAI#5969] opened 2024-03-15 17:14 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### Operating system

Linux

### GPU vendor

Nvidia (CUDA)

### GPU model

Tesla P40

### GPU VRAM

24GB

### Version number

4.0.0rc2

### Browser

Chrome 122.0.6261.128

### What happened

When using an infinite canvas in img2img or outpainting mode, the generated image is shifted relative to the original image. This is especially bad when only part of the original image is selected for generation.

![image](https://github.com/invoke-ai/InvokeAI/assets/135327897/08de1ed1-b032-4443-b91e-6bddaa74a956)
As you can see in the image, I have only selected a portion of the original image.

![image](https://github.com/invoke-ai/InvokeAI/assets/135327897/6c8e13cc-525a-4e03-82aa-4154d0cd476c)
And during and after generation, the generated part shifted.

### What you expected to happen

?
I expected there would be no image shift.

### Discord username

Vasyanator

**Comment by psychedelicious** [comment] 2024-03-20 03:25
Confirmed this is an issue - just ran into it. Haven't figured out how to reliably reproduce it yet.

**Comment by makemefeelgr8** [comment] 2024-03-23 22:14
Same happens when you set the selection box size to be less than 512x512. Make it small, drag it around, and it starts failing. Surprisingly, restarting the app fixed it for me. The issue might be related to uploading external images by dragging VS sending them to canvas from inside the app.

**Comment by joshistoast** [comment] 2024-03-24 18:06
This happens to me sometimes (a lot) and the easiest solution is to discard the current intermediates, save the changes and send the saved image to unified canvas.

**Comment by giladosk** [comment] 2024-04-02 12:03
Happened to me as well, had to scrap the current staged configuration and re-create it

**Comment by psychedelicious** [comment] 2024-04-02 12:49
More information: https://discord.com/channels/1020123559063990373/1223733113029529652/1223733113029529652

I tried a number of things today to reproduce this:
- Induced an invocation error
- Induced a queue item error
- Small bounding box, moving it around, generating, etc
- Dragging different sized images in from gallery
- Send to canvas (this is the same internal logic as dragging from gallery)

Couldn't trigger it once. I believe it's a real problem, just need to figure out how to repro it to fix it.

**Comment by ufuksarp** [comment] 2024-04-05 21:56
I’ll test this tomorrow with masks. It was happening mostly with masks since 3.3 for me which was the first version I used.

**Comment by ufuksarp** [comment] 2024-04-06 12:16
I tested a bit today and managed to find only one way to consistently reproduce this behaviour:

1. Send an image to the canvas.
2. Generate. (I2I, or inpaint, doesn't matter)
3. **Click `Cancel Current Item` before generation finishes.**
4. Resize or move the bounding box.
5. Generate.
6. Step 4 seems ignored.

Seems that cancelling current item blocks something to be rewritten? Some state is not reset but others are? Just a guess. Clicking `Discard Current` or `Discard All` after generation fixes it, next generations seems correct.

**Closed** 2024-04-10 11:48 UTC
Labels: bug
