### ISSUE TITLE
[bug]: Can we get a one time Install thing ? "caught was: No module named 'triton'"

### ISSUE THREAD

**Issue by LubuLubu2** [invoke-ai/InvokeAI#4166] opened 2023-08-05 10:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS

Windows

### GPU

cuda

### What version did you experience this issue on?

3.0.1

### What happened?

Error caught was: No module named 'triton'

Can we get some Extract and Run Portable version ? 
InvokeAI and WebUI are killing me. How many times i have to Download ~3GB Torch ? how many times i have to wait almost an hour for Toch to Install while the whole PC is forzen and all i can do is to watch an Ugly cmd window ? Why are there so many downloads ? i specifically said no model download and uncheked all of them but i downloaded +4GB data anyways. and after all of that "Error caught was: No module named 'triton'" happened. doesn't matter if i ignore it or run another command, i get a bunch of errors and another "Error caught was: No module named 'triton'" loop.

Download ~3GB Torch...
Wait almost an hour for Torch...
Download a bunch of unwanted Models, one ~2GB, Another Torch whatever 1.7GB, and another Torch dot whatever around 1.5GB.... 
Everything is set to go...
Error caught was: No module named 'triton'....
Run re-Install....
re-Installing Torch while everything is frozen...
Same Error....

**Comment by Millu** [comment] 2023-08-05 23:50
Could you share the terminal output once you hit [1] to start using Invoke?

**Comment by mohamedaleya** [comment] 2023-08-06 20:33
Just had this error too
I'm still installing the models though. Will update this comment once everything is setup.
I do agree with you that it would be great to have a Portable version as an alternative.

![WindowsTerminal_3CSsxcNniu](https://github.com/invoke-ai/InvokeAI/assets/43639707/36e0eaaf-19b9-4231-bfd9-5efb25199049)

**Comment by Millu** [comment] 2023-08-07 04:06
@mohamedaleya @LubuLubu2 you should be able to ignore the Triton error message on windows - try going ahead and using the WebUI and see if you run into any issues

**Comment by LubuLubu2** [comment] 2023-08-07 05:32
@Millu Millu 
Sorry man i deleted Invoke and don't have the files anymore. Option 1 to 10 were the same, none of them did anything, same loop.

**Comment by FilipTrichkov** [comment] 2023-08-07 14:06
I have the same issue as well when I launch invoke.bat, I can still generate images in the WebUI but it is signifcantly slower. I thought this was an issue because I did not update from 2.3.5 to 3.0.1 properly but I still can generate images so I am not sure.  I tried installing triton in my new Invoke 3 directory with the 'pip install triton' command, but I was left with this message "ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton"
<img width="512" alt="Screenshot 2023-08-07 160441" src="https://github.com/invoke-ai/InvokeAI/assets/61379159/170a7f3d-a32d-4e54-bc83-9e47c9a7d1e0">

**Comment by mohamedaleya** [comment] 2023-08-09 00:57
> @Millu Millu 
> 
> Sorry man i deleted Invoke and don't have the files anymore. Option 1 to 10 were the same, none of them did anything, same loop.

Same here. Ended up deleting entirely cause I kept getting an error saying no module named "invokeai" after downloading about 32gb of files, whenever I press any option in the menu.

**Comment by bigsk1** [comment] 2023-08-19 06:19
Same error fresh install, webui works but... errors bug me

Please enter 1-10, Q: [1] 1
Starting the InvokeAI browser-based UI..
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
[2023-08-18 23:19:09,046]::[InvokeAI]::INFO --> Patchmatch initialized
X:\InvokeAI\InvokeAI-Installer\invoke\.venv\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[2023-08-18 23:19:11,647]::[uvicorn.error]::INFO --> Started server process [23512]
[2023-08-18 23:19:11,650]::[uvicorn.error]::INFO --> Waiting for application startup.
[2023-08-18 23:19:11,652]::[InvokeAI]::INFO --> InvokeAI version 3.0.2post1
[2023-08-18 23:19:11,663]::[InvokeAI]::INFO --> Root directory = X:\InvokeAI\InvokeAI-Installer\invoke
[2023-08-18 23:19:11,671]::[InvokeAI]::INFO --> GPU device = cuda NVIDIA GeForce RTX 4090
[2023-08-18 23:19:11,721]::[InvokeAI]::INFO --> Scanning X:\InvokeAI\InvokeAI-Installer\invoke\models for new models
[2023-08-18 23:19:11,975]::[InvokeAI]::INFO --> Scanned 5 files and directories, imported 0 models
[2023-08-18 23:19:12,017]::[InvokeAI]::INFO --> Model manager service initialized
[2023-08-18 23:19:12,045]::[uvicorn.error]::INFO --> Application startup complete.
[2023-08-18 23:19:12,046]::[uvicorn.error]::INFO --> Uvicorn running on http://127.0.0.1:9090 (Press CTRL+C to quit)

**Comment by Harvester62** [comment] 2024-02-07 16:44
Both messages are not a problem under Windows. Simply ignore them. Therefore, if these were the only reported problems, they are not a bug per se, so we might consider to close this bug report.

**Closed** 2024-04-27 10:13 UTC
Labels: bug
